<a href="https://colab.research.google.com/github/vaniatharv/AccidentLens/blob/main/Accident_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# setup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)

In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
!pip install opencv-python

Requirement already satisfied: opencv-python in /usr/local/lib/python3.12/dist-packages (4.12.0.88)
Requirement already satisfied: numpy<2.3.0,>=2 in /usr/local/lib/python3.12/dist-packages (from opencv-python) (2.0.2)

In [ ]:
import pandas as pd

csv_path = "/content/drive/MyDrive/train.csv"
df = pd.read_csv(csv_path)
df.head()

            filename      case  duration
0   accident_000.mp4  accident      8.31
1   accident_001.mp4  accident      5.35
2  accident_0010.mp4  accident      6.71
3  accident_0011.mp4  accident      6.40
4  accident_0012.mp4  accident      7.08

In [ ]:
df['case'].values_counts()

case
accident    68
driving     68
Name: count, dtype: int64

# extract frames

In [ ]:
import cv2, os
from tqdm import tqdm

def extract_frames(video_path, output_folder, every_n_frames=10):
  os.makedirs(output_folder, exist_ok=True)
  cap = cv2.VideoCapture(video_path)
  frame_id, count = 0, 0

  while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
      break
    if frame_id % every_n_frames == 0:
      frame_path = os.path.join(output_folder, f"frame_{count}.jpg")
      cv2.imwrite(frame_path, frame)
      count += 1
    frame_id += 1

  cap.release()

base_video_dir = "/content/drive/MyDrive/train/training_videos"
base_frame_dir = "/content/drive/MyDrive/train/training_frames"

for video_file, row in tqdm(df.iterrows(), total=len(df)):
  video_file = os.path.join(base_video_dir, row['filename'])
  label = row['case']
  output_folder = os.path.join(base_frame_dir, label, row['filename'].split('.')[0])
  extract_frames(video_file, output_folder, every_n_frames =10)

100%|██████████| 136/136 [03:13<00:00,  1.42s/it]

# feature extraction

In [ ]:
!pip install keras

Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras) (0.5.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras) (25.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image
import glob

In [ ]:
# Load the pre-trained EfficientNetB0 model
model = EfficientNetB0(weights='imagenet', include_top=False, pooling='avg')

def extract_features_from_frame(frame_path):
    img = image.load_img(frame_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)
    features = model.predict(img_array)
    return features.flatten()

# Directory containing the extracted frames
base_frame_dir = "/content/drive/MyDrive/train/training_frames"

# Dictionary to store features
video_features = {}

# Iterate through each video folder and extract features from frames
for case_folder in os.listdir(base_frame_dir):
    case_path = os.path.join(base_frame_dir, case_folder)
    if os.path.isdir(case_path):
        for video_folder in os.listdir(case_path):
            video_path = os.path.join(case_path, video_folder)
            if os.path.isdir(video_path):
                frame_files = glob.glob(os.path.join(video_path, "*.jpg"))
                frame_features = [extract_features_from_frame(frame_file) for frame_file in tqdm(frame_files, desc=f"Extracting features for {video_folder}")]
                video_features[video_folder] = np.array(frame_features)

Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step

Extracting features for accident_000:   0%|          | 0/25 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step

Extracting features for accident_000:   4%|▍         | 1/25 [00:03<01:16,  3.20s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_000:   8%|▊         | 2/25 [00:03<00:33,  1.44s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_000:  12%|█▏        | 3/25 [00:03<00:19,  1.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_000:  16%|█▌        | 4/25 [00:03<00:12,  1.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_000:  20%|██        | 5/25 [00:03<00:08,  2.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_000:  24%|██▍       | 6/25 [00:04<00:06,  2.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_000:  28%|██▊       | 7/25 [00:04<00:05,  3.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_000:  32%|███▏      | 8/25 [00:04<00:04,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_000:  36%|███▌      | 9/25 [00:04<00:03,  4.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_000:  40%|████      | 10/25 [00:04<00:02,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_000:  44%|████▍     | 11/25 [00:04<00:02,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_000:  48%|████▊     | 12/25 [00:05<00:02,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_000:  52%|█████▏    | 13/25 [00:05<00:02,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_000:  56%|█████▌    | 14/25 [00:05<00:01,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_000:  60%|██████    | 15/25 [00:05<00:01,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_000:  64%|██████▍   | 16/25 [00:05<00:01,  6.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_000:  68%|██████▊   | 17/25 [00:05<00:01,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_000:  72%|███████▏  | 18/25 [00:05<00:01,  6.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_000:  76%|███████▌  | 19/25 [00:06<00:00,  6.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_000:  80%|████████  | 20/25 [00:06<00:00,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_000:  84%|████████▍ | 21/25 [00:06<00:00,  6.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_000:  88%|████████▊ | 22/25 [00:06<00:00,  6.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_000:  92%|█████████▏| 23/25 [00:06<00:00,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_000:  96%|█████████▌| 24/25 [00:06<00:00,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_000: 100%|██████████| 25/25 [00:07<00:00,  3.53it/s]
Extracting features for accident_001:   0%|          | 0/16 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_001:   6%|▋         | 1/16 [00:00<00:02,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_001:  12%|█▎        | 2/16 [00:00<00:02,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_001:  19%|█▉        | 3/16 [00:00<00:01,  6.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_001:  25%|██▌       | 4/16 [00:00<00:01,  6.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_001:  31%|███▏      | 5/16 [00:00<00:01,  6.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_001:  38%|███▊      | 6/16 [00:00<00:01,  6.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_001:  44%|████▍     | 7/16 [00:01<00:01,  6.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_001:  50%|█████     | 8/16 [00:01<00:01,  6.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_001:  56%|█████▋    | 9/16 [00:01<00:01,  5.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_001:  62%|██████▎   | 10/16 [00:01<00:01,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_001:  69%|██████▉   | 11/16 [00:01<00:00,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_001:  75%|███████▌  | 12/16 [00:01<00:00,  6.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_001:  81%|████████▏ | 13/16 [00:02<00:00,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_001:  88%|████████▊ | 14/16 [00:02<00:00,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_001:  94%|█████████▍| 15/16 [00:02<00:00,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_001: 100%|██████████| 16/16 [00:02<00:00,  6.32it/s]
Extracting features for accident_0010:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0010:   5%|▌         | 1/20 [00:00<00:02,  6.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0010:  10%|█         | 2/20 [00:00<00:02,  6.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0010:  15%|█▌        | 3/20 [00:00<00:02,  6.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0010:  20%|██        | 4/20 [00:00<00:02,  6.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0010:  25%|██▌       | 5/20 [00:00<00:02,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0010:  30%|███       | 6/20 [00:00<00:02,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0010:  35%|███▌      | 7/20 [00:01<00:01,  6.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0010:  40%|████      | 8/20 [00:01<00:01,  6.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0010:  45%|████▌     | 9/20 [00:01<00:01,  6.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0010:  50%|█████     | 10/20 [00:01<00:01,  6.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0010:  55%|█████▌    | 11/20 [00:01<00:01,  6.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0010:  60%|██████    | 12/20 [00:01<00:01,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

Extracting features for accident_0010:  65%|██████▌   | 13/20 [00:02<00:01,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0010:  70%|███████   | 14/20 [00:02<00:01,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0010:  75%|███████▌  | 15/20 [00:02<00:01,  4.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

Extracting features for accident_0010:  80%|████████  | 16/20 [00:02<00:00,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

Extracting features for accident_0010:  85%|████████▌ | 17/20 [00:02<00:00,  4.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0010:  90%|█████████ | 18/20 [00:03<00:00,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0010:  95%|█████████▌| 19/20 [00:03<00:00,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0010: 100%|██████████| 20/20 [00:03<00:00,  5.40it/s]
Extracting features for accident_0011:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step

Extracting features for accident_0011:   5%|▌         | 1/20 [00:00<00:04,  3.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step

Extracting features for accident_0011:  10%|█         | 2/20 [00:00<00:06,  2.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

Extracting features for accident_0011:  15%|█▌        | 3/20 [00:00<00:04,  3.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_0011:  20%|██        | 4/20 [00:01<00:04,  3.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_0011:  25%|██▌       | 5/20 [00:01<00:03,  3.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0011:  30%|███       | 6/20 [00:01<00:03,  4.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

Extracting features for accident_0011:  35%|███▌      | 7/20 [00:01<00:03,  4.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0011:  40%|████      | 8/20 [00:02<00:02,  4.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0011:  45%|████▌     | 9/20 [00:02<00:02,  4.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0011:  50%|█████     | 10/20 [00:02<00:02,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0011:  55%|█████▌    | 11/20 [00:02<00:01,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0011:  60%|██████    | 12/20 [00:02<00:01,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0011:  65%|██████▌   | 13/20 [00:02<00:01,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0011:  70%|███████   | 14/20 [00:02<00:00,  6.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0011:  75%|███████▌  | 15/20 [00:03<00:00,  6.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0011:  80%|████████  | 16/20 [00:03<00:00,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step

Extracting features for accident_0011:  85%|████████▌ | 17/20 [00:03<00:00,  4.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 236ms/step

Extracting features for accident_0011:  90%|█████████ | 18/20 [00:04<00:00,  3.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step

Extracting features for accident_0011:  95%|█████████▌| 19/20 [00:04<00:00,  2.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 301ms/step

Extracting features for accident_0011: 100%|██████████| 20/20 [00:05<00:00,  3.79it/s]
Extracting features for accident_0012:   0%|          | 0/22 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step

Extracting features for accident_0012:   5%|▍         | 1/22 [00:00<00:11,  1.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step

Extracting features for accident_0012:   9%|▉         | 2/22 [00:01<00:10,  1.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step

Extracting features for accident_0012:  14%|█▎        | 3/22 [00:01<00:09,  2.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for accident_0012:  18%|█▊        | 4/22 [00:01<00:07,  2.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0012:  23%|██▎       | 5/22 [00:01<00:05,  3.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0012:  27%|██▋       | 6/22 [00:02<00:04,  3.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0012:  32%|███▏      | 7/22 [00:02<00:03,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_0012:  36%|███▋      | 8/22 [00:02<00:02,  4.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0012:  41%|████      | 9/22 [00:02<00:02,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0012:  45%|████▌     | 10/22 [00:02<00:02,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0012:  50%|█████     | 11/22 [00:02<00:01,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0012:  55%|█████▍    | 12/22 [00:03<00:01,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0012:  59%|█████▉    | 13/22 [00:03<00:01,  6.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0012:  64%|██████▎   | 14/22 [00:03<00:01,  6.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0012:  68%|██████▊   | 15/22 [00:03<00:01,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0012:  73%|███████▎  | 16/22 [00:03<00:00,  6.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0012:  77%|███████▋  | 17/22 [00:03<00:00,  6.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0012:  82%|████████▏ | 18/22 [00:03<00:00,  6.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0012:  86%|████████▋ | 19/22 [00:04<00:00,  6.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0012:  91%|█████████ | 20/22 [00:04<00:00,  6.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0012:  95%|█████████▌| 21/22 [00:04<00:00,  6.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0012: 100%|██████████| 22/22 [00:04<00:00,  4.85it/s]
Extracting features for accident_0013:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0013:   5%|▌         | 1/20 [00:00<00:02,  6.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0013:  10%|█         | 2/20 [00:00<00:02,  6.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0013:  15%|█▌        | 3/20 [00:00<00:02,  6.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0013:  20%|██        | 4/20 [00:00<00:02,  6.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0013:  25%|██▌       | 5/20 [00:00<00:02,  6.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0013:  30%|███       | 6/20 [00:00<00:02,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_0013:  35%|███▌      | 7/20 [00:01<00:02,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0013:  40%|████      | 8/20 [00:01<00:01,  6.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0013:  45%|████▌     | 9/20 [00:01<00:01,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0013:  50%|█████     | 10/20 [00:01<00:01,  6.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0013:  55%|█████▌    | 11/20 [00:01<00:01,  6.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0013:  60%|██████    | 12/20 [00:01<00:01,  6.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0013:  65%|██████▌   | 13/20 [00:02<00:01,  6.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for accident_0013:  70%|███████   | 14/20 [00:02<00:01,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0013:  75%|███████▌  | 15/20 [00:02<00:00,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0013:  80%|████████  | 16/20 [00:02<00:00,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0013:  85%|████████▌ | 17/20 [00:02<00:00,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for accident_0013:  90%|█████████ | 18/20 [00:03<00:00,  4.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_0013:  95%|█████████▌| 19/20 [00:03<00:00,  4.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0013: 100%|██████████| 20/20 [00:03<00:00,  5.48it/s]
Extracting features for accident_0014:   0%|          | 0/18 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

Extracting features for accident_0014:   6%|▌         | 1/18 [00:00<00:03,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0014:  11%|█         | 2/18 [00:00<00:03,  4.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

Extracting features for accident_0014:  17%|█▋        | 3/18 [00:00<00:03,  4.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0014:  22%|██▏       | 4/18 [00:00<00:03,  4.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for accident_0014:  28%|██▊       | 5/18 [00:01<00:02,  4.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

Extracting features for accident_0014:  33%|███▎      | 6/18 [00:01<00:02,  4.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for accident_0014:  39%|███▉      | 7/18 [00:01<00:03,  3.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0014:  44%|████▍     | 8/18 [00:01<00:02,  3.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0014:  50%|█████     | 9/18 [00:02<00:02,  3.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0014:  56%|█████▌    | 10/18 [00:02<00:01,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0014:  61%|██████    | 11/18 [00:02<00:01,  4.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0014:  67%|██████▋   | 12/18 [00:02<00:01,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0014:  72%|███████▏  | 13/18 [00:02<00:00,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0014:  78%|███████▊  | 14/18 [00:02<00:00,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0014:  83%|████████▎ | 15/18 [00:03<00:00,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0014:  89%|████████▉ | 16/18 [00:03<00:00,  6.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0014:  94%|█████████▍| 17/18 [00:03<00:00,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0014: 100%|██████████| 18/18 [00:03<00:00,  4.94it/s]
Extracting features for accident_0015:   0%|          | 0/15 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0015:   7%|▋         | 1/15 [00:00<00:02,  6.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0015:  13%|█▎        | 2/15 [00:00<00:02,  6.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0015:  20%|██        | 3/15 [00:00<00:01,  6.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0015:  27%|██▋       | 4/15 [00:00<00:01,  6.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0015:  33%|███▎      | 5/15 [00:00<00:01,  6.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0015:  40%|████      | 6/15 [00:00<00:01,  6.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0015:  47%|████▋     | 7/15 [00:01<00:01,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0015:  53%|█████▎    | 8/15 [00:01<00:01,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0015:  60%|██████    | 9/15 [00:01<00:00,  6.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0015:  67%|██████▋   | 10/15 [00:01<00:00,  6.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0015:  73%|███████▎  | 11/15 [00:01<00:00,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0015:  80%|████████  | 12/15 [00:01<00:00,  6.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0015:  87%|████████▋ | 13/15 [00:01<00:00,  6.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0015:  93%|█████████▎| 14/15 [00:02<00:00,  6.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0015: 100%|██████████| 15/15 [00:02<00:00,  6.51it/s]
Extracting features for accident_0016:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0016:   8%|▊         | 1/13 [00:00<00:01,  6.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0016:  15%|█▌        | 2/13 [00:00<00:01,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0016:  23%|██▎       | 3/13 [00:00<00:01,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0016:  31%|███       | 4/13 [00:00<00:01,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_0016:  38%|███▊      | 5/13 [00:00<00:01,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0016:  46%|████▌     | 6/13 [00:00<00:01,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0016:  54%|█████▍    | 7/13 [00:01<00:00,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0016:  62%|██████▏   | 8/13 [00:01<00:00,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0016:  69%|██████▉   | 9/13 [00:01<00:00,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0016:  77%|███████▋  | 10/13 [00:01<00:00,  6.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0016:  85%|████████▍ | 11/13 [00:01<00:00,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0016:  92%|█████████▏| 12/13 [00:01<00:00,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0016: 100%|██████████| 13/13 [00:02<00:00,  6.05it/s]
Extracting features for accident_0017:   0%|          | 0/15 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0017:   7%|▋         | 1/15 [00:00<00:02,  5.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0017:  13%|█▎        | 2/15 [00:00<00:02,  6.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0017:  20%|██        | 3/15 [00:00<00:01,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0017:  27%|██▋       | 4/15 [00:00<00:01,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0017:  33%|███▎      | 5/15 [00:00<00:01,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0017:  40%|████      | 6/15 [00:00<00:01,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0017:  47%|████▋     | 7/15 [00:01<00:01,  6.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0017:  53%|█████▎    | 8/15 [00:01<00:01,  6.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0017:  60%|██████    | 9/15 [00:01<00:00,  6.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0017:  67%|██████▋   | 10/15 [00:01<00:00,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0017:  73%|███████▎  | 11/15 [00:01<00:00,  6.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0017:  80%|████████  | 12/15 [00:01<00:00,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0017:  87%|████████▋ | 13/15 [00:02<00:00,  5.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0017:  93%|█████████▎| 14/15 [00:02<00:00,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0017: 100%|██████████| 15/15 [00:02<00:00,  6.26it/s]
Extracting features for accident_0018:   0%|          | 0/23 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0018:   4%|▍         | 1/23 [00:00<00:03,  6.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step

Extracting features for accident_0018:   9%|▊         | 2/23 [00:00<00:03,  6.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0018:  13%|█▎        | 3/23 [00:00<00:03,  6.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0018:  17%|█▋        | 4/23 [00:00<00:03,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0018:  22%|██▏       | 5/23 [00:00<00:03,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0018:  26%|██▌       | 6/23 [00:01<00:02,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0018:  30%|███       | 7/23 [00:01<00:02,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0018:  35%|███▍      | 8/23 [00:01<00:02,  6.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0018:  39%|███▉      | 9/23 [00:01<00:02,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0018:  43%|████▎     | 10/23 [00:01<00:02,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for accident_0018:  48%|████▊     | 11/23 [00:01<00:02,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

Extracting features for accident_0018:  52%|█████▏    | 12/23 [00:02<00:02,  5.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

Extracting features for accident_0018:  57%|█████▋    | 13/23 [00:02<00:02,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0018:  61%|██████    | 14/23 [00:02<00:01,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0018:  65%|██████▌   | 15/23 [00:02<00:01,  4.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

Extracting features for accident_0018:  70%|██████▉   | 16/23 [00:02<00:01,  4.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

Extracting features for accident_0018:  74%|███████▍  | 17/23 [00:03<00:01,  4.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for accident_0018:  78%|███████▊  | 18/23 [00:03<00:01,  4.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0018:  83%|████████▎ | 19/23 [00:03<00:00,  4.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for accident_0018:  87%|████████▋ | 20/23 [00:03<00:00,  4.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

Extracting features for accident_0018:  91%|█████████▏| 21/23 [00:04<00:00,  4.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0018:  96%|█████████▌| 22/23 [00:04<00:00,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0018: 100%|██████████| 23/23 [00:04<00:00,  5.01it/s]
Extracting features for accident_0019:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0019:   5%|▌         | 1/20 [00:00<00:04,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0019:  10%|█         | 2/20 [00:00<00:04,  4.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for accident_0019:  15%|█▌        | 3/20 [00:00<00:04,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

Extracting features for accident_0019:  20%|██        | 4/20 [00:00<00:03,  4.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0019:  25%|██▌       | 5/20 [00:01<00:03,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0019:  30%|███       | 6/20 [00:01<00:02,  5.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0019:  35%|███▌      | 7/20 [00:01<00:02,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0019:  40%|████      | 8/20 [00:01<00:02,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0019:  45%|████▌     | 9/20 [00:01<00:01,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0019:  50%|█████     | 10/20 [00:01<00:01,  6.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0019:  55%|█████▌    | 11/20 [00:02<00:01,  6.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0019:  60%|██████    | 12/20 [00:02<00:01,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0019:  65%|██████▌   | 13/20 [00:02<00:01,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0019:  70%|███████   | 14/20 [00:02<00:00,  6.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0019:  75%|███████▌  | 15/20 [00:02<00:00,  6.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0019:  80%|████████  | 16/20 [00:02<00:00,  6.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0019:  85%|████████▌ | 17/20 [00:03<00:00,  6.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0019:  90%|█████████ | 18/20 [00:03<00:00,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0019:  95%|█████████▌| 19/20 [00:03<00:00,  6.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0019: 100%|██████████| 20/20 [00:03<00:00,  5.62it/s]
Extracting features for accident_002:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_002:   8%|▊         | 1/13 [00:00<00:01,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_002:  15%|█▌        | 2/13 [00:00<00:01,  6.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_002:  23%|██▎       | 3/13 [00:00<00:01,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_002:  31%|███       | 4/13 [00:00<00:01,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_002:  38%|███▊      | 5/13 [00:00<00:01,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_002:  46%|████▌     | 6/13 [00:00<00:01,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_002:  54%|█████▍    | 7/13 [00:01<00:01,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_002:  62%|██████▏   | 8/13 [00:01<00:00,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_002:  69%|██████▉   | 9/13 [00:01<00:00,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_002:  77%|███████▋  | 10/13 [00:01<00:00,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_002:  85%|████████▍ | 11/13 [00:01<00:00,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_002:  92%|█████████▏| 12/13 [00:02<00:00,  5.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_002: 100%|██████████| 13/13 [00:02<00:00,  5.50it/s]
Extracting features for accident_0020:   0%|          | 0/23 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0020:   4%|▍         | 1/23 [00:00<00:03,  6.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0020:   9%|▊         | 2/23 [00:00<00:03,  6.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0020:  13%|█▎        | 3/23 [00:00<00:03,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0020:  17%|█▋        | 4/23 [00:00<00:03,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0020:  22%|██▏       | 5/23 [00:00<00:03,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0020:  26%|██▌       | 6/23 [00:01<00:02,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0020:  30%|███       | 7/23 [00:01<00:02,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0020:  35%|███▍      | 8/23 [00:01<00:02,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0020:  39%|███▉      | 9/23 [00:01<00:02,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0020:  43%|████▎     | 10/23 [00:01<00:02,  6.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0020:  48%|████▊     | 11/23 [00:01<00:01,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0020:  52%|█████▏    | 12/23 [00:02<00:01,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0020:  57%|█████▋    | 13/23 [00:02<00:01,  5.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0020:  61%|██████    | 14/23 [00:02<00:01,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0020:  65%|██████▌   | 15/23 [00:02<00:01,  6.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0020:  70%|██████▉   | 16/23 [00:02<00:01,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0020:  74%|███████▍  | 17/23 [00:02<00:01,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0020:  78%|███████▊  | 18/23 [00:02<00:00,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0020:  83%|████████▎ | 19/23 [00:03<00:00,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0020:  87%|████████▋ | 20/23 [00:03<00:00,  6.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0020:  91%|█████████▏| 21/23 [00:03<00:00,  6.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0020:  96%|█████████▌| 22/23 [00:03<00:00,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0020: 100%|██████████| 23/23 [00:03<00:00,  6.02it/s]
Extracting features for accident_0021:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0021:   5%|▌         | 1/20 [00:00<00:03,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0021:  10%|█         | 2/20 [00:00<00:03,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0021:  15%|█▌        | 3/20 [00:00<00:02,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0021:  20%|██        | 4/20 [00:00<00:02,  5.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0021:  25%|██▌       | 5/20 [00:00<00:02,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0021:  30%|███       | 6/20 [00:01<00:02,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0021:  35%|███▌      | 7/20 [00:01<00:02,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0021:  40%|████      | 8/20 [00:01<00:02,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for accident_0021:  45%|████▌     | 9/20 [00:01<00:02,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_0021:  50%|█████     | 10/20 [00:01<00:02,  4.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0021:  55%|█████▌    | 11/20 [00:02<00:01,  4.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_0021:  60%|██████    | 12/20 [00:02<00:01,  4.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for accident_0021:  65%|██████▌   | 13/20 [00:02<00:01,  3.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_0021:  70%|███████   | 14/20 [00:03<00:01,  3.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0021:  75%|███████▌  | 15/20 [00:03<00:01,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for accident_0021:  80%|████████  | 16/20 [00:03<00:01,  3.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0021:  85%|████████▌ | 17/20 [00:03<00:00,  4.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_0021:  90%|█████████ | 18/20 [00:04<00:00,  3.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for accident_0021:  95%|█████████▌| 19/20 [00:04<00:00,  4.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0021: 100%|██████████| 20/20 [00:04<00:00,  4.46it/s]
Extracting features for accident_0022:   0%|          | 0/29 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_0022:   3%|▎         | 1/29 [00:00<00:07,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0022:   7%|▋         | 2/29 [00:00<00:06,  4.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0022:  10%|█         | 3/29 [00:00<00:06,  4.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0022:  14%|█▍        | 4/29 [00:00<00:05,  4.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0022:  17%|█▋        | 5/29 [00:01<00:05,  4.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0022:  21%|██        | 6/29 [00:01<00:04,  4.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0022:  24%|██▍       | 7/29 [00:01<00:04,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0022:  28%|██▊       | 8/29 [00:01<00:04,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0022:  31%|███       | 9/29 [00:01<00:03,  5.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0022:  34%|███▍      | 10/29 [00:02<00:03,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0022:  38%|███▊      | 11/29 [00:02<00:03,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0022:  41%|████▏     | 12/29 [00:02<00:03,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0022:  45%|████▍     | 13/29 [00:02<00:02,  5.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0022:  48%|████▊     | 14/29 [00:02<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0022:  52%|█████▏    | 15/29 [00:02<00:02,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0022:  55%|█████▌    | 16/29 [00:03<00:02,  5.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0022:  59%|█████▊    | 17/29 [00:03<00:01,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0022:  62%|██████▏   | 18/29 [00:03<00:01,  6.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0022:  66%|██████▌   | 19/29 [00:03<00:01,  6.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0022:  69%|██████▉   | 20/29 [00:03<00:01,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0022:  72%|███████▏  | 21/29 [00:03<00:01,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0022:  76%|███████▌  | 22/29 [00:04<00:01,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0022:  79%|███████▉  | 23/29 [00:04<00:00,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0022:  83%|████████▎ | 24/29 [00:04<00:00,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0022:  86%|████████▌ | 25/29 [00:04<00:00,  6.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0022:  90%|████████▉ | 26/29 [00:04<00:00,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0022:  93%|█████████▎| 27/29 [00:04<00:00,  5.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0022:  97%|█████████▋| 28/29 [00:05<00:00,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step

Extracting features for accident_0022: 100%|██████████| 29/29 [00:05<00:00,  5.37it/s]
Extracting features for accident_0023:   0%|          | 0/38 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0023:   3%|▎         | 1/38 [00:00<00:05,  6.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_0023:   5%|▌         | 2/38 [00:00<00:05,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0023:   8%|▊         | 3/38 [00:00<00:05,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0023:  11%|█         | 4/38 [00:00<00:05,  6.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0023:  13%|█▎        | 5/38 [00:00<00:05,  6.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0023:  16%|█▌        | 6/38 [00:00<00:04,  6.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0023:  18%|█▊        | 7/38 [00:01<00:05,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0023:  21%|██        | 8/38 [00:01<00:05,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0023:  24%|██▎       | 9/38 [00:01<00:05,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0023:  26%|██▋       | 10/38 [00:01<00:04,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0023:  29%|██▉       | 11/38 [00:01<00:04,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0023:  32%|███▏      | 12/38 [00:02<00:04,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0023:  34%|███▍      | 13/38 [00:02<00:04,  5.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0023:  37%|███▋      | 14/38 [00:02<00:04,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0023:  39%|███▉      | 15/38 [00:02<00:03,  6.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0023:  42%|████▏     | 16/38 [00:02<00:03,  5.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0023:  45%|████▍     | 17/38 [00:02<00:03,  5.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0023:  47%|████▋     | 18/38 [00:03<00:03,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0023:  50%|█████     | 19/38 [00:03<00:03,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0023:  53%|█████▎    | 20/38 [00:03<00:02,  6.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0023:  55%|█████▌    | 21/38 [00:03<00:02,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step

Extracting features for accident_0023:  58%|█████▊    | 22/38 [00:03<00:02,  6.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0023:  61%|██████    | 23/38 [00:03<00:02,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0023:  63%|██████▎   | 24/38 [00:04<00:02,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0023:  66%|██████▌   | 25/38 [00:04<00:02,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_0023:  68%|██████▊   | 26/38 [00:04<00:02,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0023:  71%|███████   | 27/38 [00:04<00:01,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0023:  74%|███████▎  | 28/38 [00:04<00:01,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0023:  76%|███████▋  | 29/38 [00:04<00:01,  5.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0023:  79%|███████▉  | 30/38 [00:05<00:01,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0023:  82%|████████▏ | 31/38 [00:05<00:01,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for accident_0023:  84%|████████▍ | 32/38 [00:05<00:01,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for accident_0023:  87%|████████▋ | 33/38 [00:05<00:00,  5.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0023:  89%|████████▉ | 34/38 [00:05<00:00,  4.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_0023:  92%|█████████▏| 35/38 [00:06<00:00,  4.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0023:  95%|█████████▍| 36/38 [00:06<00:00,  4.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0023:  97%|█████████▋| 37/38 [00:06<00:00,  4.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for accident_0023: 100%|██████████| 38/38 [00:06<00:00,  5.49it/s]
Extracting features for accident_0024:   0%|          | 0/14 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_0024:   7%|▋         | 1/14 [00:00<00:03,  4.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

Extracting features for accident_0024:  14%|█▍        | 2/14 [00:00<00:02,  4.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_0024:  21%|██▏       | 3/14 [00:00<00:02,  4.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0024:  29%|██▊       | 4/14 [00:00<00:02,  4.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for accident_0024:  36%|███▌      | 5/14 [00:01<00:02,  4.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

Extracting features for accident_0024:  43%|████▎     | 6/14 [00:01<00:01,  4.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0024:  50%|█████     | 7/14 [00:01<00:01,  4.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_0024:  57%|█████▋    | 8/14 [00:01<00:01,  4.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0024:  64%|██████▍   | 9/14 [00:02<00:01,  4.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

Extracting features for accident_0024:  71%|███████▏  | 10/14 [00:02<00:00,  4.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0024:  79%|███████▊  | 11/14 [00:02<00:00,  4.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0024:  86%|████████▌ | 12/14 [00:02<00:00,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_0024:  93%|█████████▎| 13/14 [00:02<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0024: 100%|██████████| 14/14 [00:03<00:00,  4.55it/s]
Extracting features for accident_0025:   0%|          | 0/21 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0025:   5%|▍         | 1/21 [00:00<00:03,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0025:  10%|▉         | 2/21 [00:00<00:02,  6.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0025:  14%|█▍        | 3/21 [00:00<00:02,  6.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0025:  19%|█▉        | 4/21 [00:00<00:02,  6.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0025:  24%|██▍       | 5/21 [00:00<00:02,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0025:  29%|██▊       | 6/21 [00:00<00:02,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0025:  33%|███▎      | 7/21 [00:01<00:02,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0025:  38%|███▊      | 8/21 [00:01<00:02,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0025:  43%|████▎     | 9/21 [00:01<00:01,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0025:  48%|████▊     | 10/21 [00:01<00:01,  6.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0025:  52%|█████▏    | 11/21 [00:01<00:01,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0025:  57%|█████▋    | 12/21 [00:01<00:01,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0025:  62%|██████▏   | 13/21 [00:02<00:01,  6.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0025:  67%|██████▋   | 14/21 [00:02<00:01,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0025:  71%|███████▏  | 15/21 [00:02<00:00,  6.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0025:  76%|███████▌  | 16/21 [00:02<00:00,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0025:  81%|████████  | 17/21 [00:02<00:00,  6.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for accident_0025:  86%|████████▌ | 18/21 [00:02<00:00,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0025:  90%|█████████ | 19/21 [00:03<00:00,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0025:  95%|█████████▌| 20/21 [00:03<00:00,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0025: 100%|██████████| 21/21 [00:03<00:00,  5.99it/s]
Extracting features for accident_0026:   0%|          | 0/24 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0026:   4%|▍         | 1/24 [00:00<00:03,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0026:   8%|▊         | 2/24 [00:00<00:03,  6.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0026:  12%|█▎        | 3/24 [00:00<00:03,  6.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0026:  17%|█▋        | 4/24 [00:00<00:03,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0026:  21%|██        | 5/24 [00:00<00:03,  6.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0026:  25%|██▌       | 6/24 [00:00<00:02,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0026:  29%|██▉       | 7/24 [00:01<00:02,  6.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0026:  33%|███▎      | 8/24 [00:01<00:02,  6.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0026:  38%|███▊      | 9/24 [00:01<00:02,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0026:  42%|████▏     | 10/24 [00:01<00:02,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0026:  46%|████▌     | 11/24 [00:01<00:02,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0026:  50%|█████     | 12/24 [00:01<00:01,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0026:  54%|█████▍    | 13/24 [00:02<00:01,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0026:  58%|█████▊    | 14/24 [00:02<00:01,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0026:  62%|██████▎   | 15/24 [00:02<00:01,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0026:  67%|██████▋   | 16/24 [00:02<00:01,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0026:  71%|███████   | 17/24 [00:02<00:01,  5.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0026:  75%|███████▌  | 18/24 [00:03<00:01,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0026:  79%|███████▉  | 19/24 [00:03<00:00,  5.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0026:  83%|████████▎ | 20/24 [00:03<00:00,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0026:  88%|████████▊ | 21/24 [00:03<00:00,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0026:  92%|█████████▏| 22/24 [00:03<00:00,  5.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0026:  96%|█████████▌| 23/24 [00:03<00:00,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0026: 100%|██████████| 24/24 [00:03<00:00,  6.05it/s]
Extracting features for accident_0027:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0027:   8%|▊         | 1/13 [00:00<00:01,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0027:  15%|█▌        | 2/13 [00:00<00:01,  6.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0027:  23%|██▎       | 3/13 [00:00<00:01,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0027:  31%|███       | 4/13 [00:00<00:01,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0027:  38%|███▊      | 5/13 [00:00<00:01,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0027:  46%|████▌     | 6/13 [00:01<00:01,  5.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0027:  54%|█████▍    | 7/13 [00:01<00:00,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0027:  62%|██████▏   | 8/13 [00:01<00:00,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0027:  69%|██████▉   | 9/13 [00:01<00:00,  6.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for accident_0027:  77%|███████▋  | 10/13 [00:01<00:00,  5.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0027:  85%|████████▍ | 11/13 [00:01<00:00,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0027:  92%|█████████▏| 12/13 [00:02<00:00,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0027: 100%|██████████| 13/13 [00:02<00:00,  5.57it/s]
Extracting features for accident_0028:   0%|          | 0/24 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0028:   4%|▍         | 1/24 [00:00<00:05,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0028:   8%|▊         | 2/24 [00:00<00:05,  3.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0028:  12%|█▎        | 3/24 [00:00<00:05,  4.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0028:  17%|█▋        | 4/24 [00:01<00:04,  4.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0028:  21%|██        | 5/24 [00:01<00:04,  4.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

Extracting features for accident_0028:  25%|██▌       | 6/24 [00:01<00:04,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0028:  29%|██▉       | 7/24 [00:01<00:04,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0028:  33%|███▎      | 8/24 [00:01<00:03,  4.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0028:  38%|███▊      | 9/24 [00:02<00:03,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for accident_0028:  42%|████▏     | 10/24 [00:02<00:03,  3.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0028:  46%|████▌     | 11/24 [00:02<00:03,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0028:  50%|█████     | 12/24 [00:02<00:03,  3.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for accident_0028:  54%|█████▍    | 13/24 [00:03<00:02,  4.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0028:  58%|█████▊    | 14/24 [00:03<00:02,  4.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for accident_0028:  62%|██████▎   | 15/24 [00:03<00:02,  4.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0028:  67%|██████▋   | 16/24 [00:03<00:01,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0028:  71%|███████   | 17/24 [00:03<00:01,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0028:  75%|███████▌  | 18/24 [00:04<00:01,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0028:  79%|███████▉  | 19/24 [00:04<00:00,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0028:  83%|████████▎ | 20/24 [00:04<00:00,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0028:  88%|████████▊ | 21/24 [00:04<00:00,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0028:  92%|█████████▏| 22/24 [00:04<00:00,  5.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0028:  96%|█████████▌| 23/24 [00:05<00:00,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0028: 100%|██████████| 24/24 [00:05<00:00,  4.64it/s]
Extracting features for accident_0029:   0%|          | 0/22 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0029:   5%|▍         | 1/22 [00:00<00:03,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0029:   9%|▉         | 2/22 [00:00<00:03,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_0029:  14%|█▎        | 3/22 [00:00<00:03,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0029:  18%|█▊        | 4/22 [00:00<00:03,  5.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0029:  23%|██▎       | 5/22 [00:00<00:02,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0029:  27%|██▋       | 6/22 [00:01<00:02,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0029:  32%|███▏      | 7/22 [00:01<00:02,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0029:  36%|███▋      | 8/22 [00:01<00:02,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_0029:  41%|████      | 9/22 [00:01<00:02,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0029:  45%|████▌     | 10/22 [00:01<00:02,  5.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0029:  50%|█████     | 11/22 [00:01<00:01,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0029:  55%|█████▍    | 12/22 [00:02<00:01,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0029:  59%|█████▉    | 13/22 [00:02<00:01,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0029:  64%|██████▎   | 14/22 [00:02<00:01,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0029:  68%|██████▊   | 15/22 [00:02<00:01,  5.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0029:  73%|███████▎  | 16/22 [00:02<00:01,  5.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0029:  77%|███████▋  | 17/22 [00:02<00:00,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0029:  82%|████████▏ | 18/22 [00:03<00:00,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0029:  86%|████████▋ | 19/22 [00:03<00:00,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step

Extracting features for accident_0029:  91%|█████████ | 20/22 [00:03<00:00,  6.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0029:  95%|█████████▌| 21/22 [00:03<00:00,  5.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0029: 100%|██████████| 22/22 [00:03<00:00,  5.88it/s]
Extracting features for accident_003:   0%|          | 0/24 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_003:   4%|▍         | 1/24 [00:00<00:03,  5.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_003:   8%|▊         | 2/24 [00:00<00:03,  6.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_003:  12%|█▎        | 3/24 [00:00<00:03,  5.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_003:  17%|█▋        | 4/24 [00:00<00:03,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_003:  21%|██        | 5/24 [00:00<00:03,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_003:  25%|██▌       | 6/24 [00:01<00:03,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_003:  29%|██▉       | 7/24 [00:01<00:02,  6.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_003:  33%|███▎      | 8/24 [00:01<00:02,  6.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_003:  38%|███▊      | 9/24 [00:01<00:02,  6.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_003:  42%|████▏     | 10/24 [00:01<00:02,  6.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_003:  46%|████▌     | 11/24 [00:01<00:02,  6.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_003:  50%|█████     | 12/24 [00:01<00:01,  6.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_003:  54%|█████▍    | 13/24 [00:02<00:01,  6.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_003:  58%|█████▊    | 14/24 [00:02<00:01,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_003:  62%|██████▎   | 15/24 [00:02<00:01,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_003:  67%|██████▋   | 16/24 [00:02<00:01,  6.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_003:  71%|███████   | 17/24 [00:02<00:01,  6.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_003:  75%|███████▌  | 18/24 [00:02<00:00,  6.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_003:  79%|███████▉  | 19/24 [00:03<00:00,  6.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_003:  83%|████████▎ | 20/24 [00:03<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_003:  88%|████████▊ | 21/24 [00:03<00:00,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_003:  92%|█████████▏| 22/24 [00:03<00:00,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_003:  96%|█████████▌| 23/24 [00:03<00:00,  5.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_003: 100%|██████████| 24/24 [00:04<00:00,  5.94it/s]
Extracting features for accident_0030:   0%|          | 0/23 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0030:   4%|▍         | 1/23 [00:00<00:03,  6.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0030:   9%|▊         | 2/23 [00:00<00:03,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0030:  13%|█▎        | 3/23 [00:00<00:03,  6.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_0030:  17%|█▋        | 4/23 [00:00<00:03,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0030:  22%|██▏       | 5/23 [00:00<00:03,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for accident_0030:  26%|██▌       | 6/23 [00:01<00:03,  4.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0030:  30%|███       | 7/23 [00:01<00:03,  4.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_0030:  35%|███▍      | 8/23 [00:01<00:03,  4.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

Extracting features for accident_0030:  39%|███▉      | 9/23 [00:01<00:03,  4.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for accident_0030:  43%|████▎     | 10/23 [00:02<00:03,  3.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for accident_0030:  48%|████▊     | 11/23 [00:02<00:03,  3.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0030:  52%|█████▏    | 12/23 [00:02<00:02,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for accident_0030:  57%|█████▋    | 13/23 [00:03<00:02,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

Extracting features for accident_0030:  61%|██████    | 14/23 [00:03<00:02,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

Extracting features for accident_0030:  65%|██████▌   | 15/23 [00:03<00:02,  3.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0030:  70%|██████▉   | 16/23 [00:03<00:01,  3.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

Extracting features for accident_0030:  74%|███████▍  | 17/23 [00:04<00:01,  4.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for accident_0030:  78%|███████▊  | 18/23 [00:04<00:01,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0030:  83%|████████▎ | 19/23 [00:04<00:01,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0030:  87%|████████▋ | 20/23 [00:04<00:00,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0030:  91%|█████████▏| 21/23 [00:04<00:00,  4.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0030:  96%|█████████▌| 22/23 [00:05<00:00,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0030: 100%|██████████| 23/23 [00:05<00:00,  4.44it/s]
Extracting features for accident_0031:   0%|          | 0/16 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for accident_0031:   6%|▋         | 1/16 [00:00<00:02,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0031:  12%|█▎        | 2/16 [00:00<00:02,  5.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0031:  19%|█▉        | 3/16 [00:00<00:02,  5.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0031:  25%|██▌       | 4/16 [00:00<00:02,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0031:  31%|███▏      | 5/16 [00:00<00:02,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0031:  38%|███▊      | 6/16 [00:01<00:01,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0031:  44%|████▍     | 7/16 [00:01<00:01,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0031:  50%|█████     | 8/16 [00:01<00:01,  5.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0031:  56%|█████▋    | 9/16 [00:01<00:01,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0031:  62%|██████▎   | 10/16 [00:01<00:01,  5.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0031:  69%|██████▉   | 11/16 [00:01<00:00,  6.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0031:  75%|███████▌  | 12/16 [00:02<00:00,  6.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0031:  81%|████████▏ | 13/16 [00:02<00:00,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0031:  88%|████████▊ | 14/16 [00:02<00:00,  6.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0031:  94%|█████████▍| 15/16 [00:02<00:00,  5.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0031: 100%|██████████| 16/16 [00:02<00:00,  5.68it/s]
Extracting features for accident_0032:   0%|          | 0/40 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0032:   2%|▎         | 1/40 [00:00<00:06,  6.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0032:   5%|▌         | 2/40 [00:00<00:06,  6.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0032:   8%|▊         | 3/40 [00:00<00:06,  6.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0032:  10%|█         | 4/40 [00:00<00:05,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0032:  12%|█▎        | 5/40 [00:00<00:05,  6.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0032:  15%|█▌        | 6/40 [00:00<00:05,  6.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0032:  18%|█▊        | 7/40 [00:01<00:05,  6.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0032:  20%|██        | 8/40 [00:01<00:05,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_0032:  22%|██▎       | 9/40 [00:01<00:05,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0032:  25%|██▌       | 10/40 [00:01<00:04,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0032:  28%|██▊       | 11/40 [00:01<00:04,  6.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0032:  30%|███       | 12/40 [00:02<00:05,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0032:  32%|███▎      | 13/40 [00:02<00:04,  5.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0032:  35%|███▌      | 14/40 [00:02<00:04,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_0032:  38%|███▊      | 15/40 [00:02<00:04,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step

Extracting features for accident_0032:  40%|████      | 16/40 [00:02<00:04,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0032:  42%|████▎     | 17/40 [00:02<00:03,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0032:  45%|████▌     | 18/40 [00:03<00:03,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0032:  48%|████▊     | 19/40 [00:03<00:03,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0032:  50%|█████     | 20/40 [00:03<00:03,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for accident_0032:  52%|█████▎    | 21/40 [00:03<00:03,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0032:  55%|█████▌    | 22/40 [00:03<00:03,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0032:  57%|█████▊    | 23/40 [00:03<00:02,  5.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0032:  60%|██████    | 24/40 [00:04<00:02,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0032:  62%|██████▎   | 25/40 [00:04<00:02,  5.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0032:  65%|██████▌   | 26/40 [00:04<00:02,  6.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0032:  68%|██████▊   | 27/40 [00:04<00:02,  6.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0032:  70%|███████   | 28/40 [00:04<00:02,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0032:  72%|███████▎  | 29/40 [00:04<00:01,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0032:  75%|███████▌  | 30/40 [00:05<00:01,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0032:  78%|███████▊  | 31/40 [00:05<00:01,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0032:  80%|████████  | 32/40 [00:05<00:01,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0032:  82%|████████▎ | 33/40 [00:05<00:01,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0032:  85%|████████▌ | 34/40 [00:05<00:01,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0032:  88%|████████▊ | 35/40 [00:06<00:00,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0032:  90%|█████████ | 36/40 [00:06<00:00,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0032:  92%|█████████▎| 37/40 [00:06<00:00,  5.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0032:  95%|█████████▌| 38/40 [00:06<00:00,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_0032:  98%|█████████▊| 39/40 [00:06<00:00,  4.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_0032: 100%|██████████| 40/40 [00:07<00:00,  5.66it/s]
Extracting features for accident_0033:   0%|          | 0/21 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0033:   5%|▍         | 1/21 [00:00<00:04,  4.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0033:  10%|▉         | 2/21 [00:00<00:04,  3.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for accident_0033:  14%|█▍        | 3/21 [00:00<00:04,  3.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0033:  19%|█▉        | 4/21 [00:00<00:04,  4.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

Extracting features for accident_0033:  24%|██▍       | 5/21 [00:01<00:04,  3.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for accident_0033:  29%|██▊       | 6/21 [00:01<00:04,  3.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for accident_0033:  33%|███▎      | 7/21 [00:01<00:03,  3.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0033:  38%|███▊      | 8/21 [00:02<00:03,  3.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

Extracting features for accident_0033:  43%|████▎     | 9/21 [00:02<00:03,  3.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for accident_0033:  48%|████▊     | 10/21 [00:02<00:03,  3.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0033:  52%|█████▏    | 11/21 [00:03<00:02,  3.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0033:  57%|█████▋    | 12/21 [00:03<00:02,  3.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0033:  62%|██████▏   | 13/21 [00:03<00:02,  3.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0033:  67%|██████▋   | 14/21 [00:03<00:01,  3.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0033:  71%|███████▏  | 15/21 [00:03<00:01,  4.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0033:  76%|███████▌  | 16/21 [00:04<00:01,  4.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0033:  81%|████████  | 17/21 [00:04<00:00,  5.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0033:  86%|████████▌ | 18/21 [00:04<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0033:  90%|█████████ | 19/21 [00:04<00:00,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0033:  95%|█████████▌| 20/21 [00:04<00:00,  5.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0033: 100%|██████████| 21/21 [00:05<00:00,  4.19it/s]
Extracting features for accident_0034:   0%|          | 0/15 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0034:   7%|▋         | 1/15 [00:00<00:02,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0034:  13%|█▎        | 2/15 [00:00<00:02,  6.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0034:  20%|██        | 3/15 [00:00<00:01,  6.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0034:  27%|██▋       | 4/15 [00:00<00:01,  6.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0034:  33%|███▎      | 5/15 [00:00<00:01,  6.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0034:  40%|████      | 6/15 [00:01<00:01,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0034:  47%|████▋     | 7/15 [00:01<00:01,  5.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0034:  53%|█████▎    | 8/15 [00:01<00:01,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0034:  60%|██████    | 9/15 [00:01<00:01,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0034:  67%|██████▋   | 10/15 [00:01<00:00,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0034:  73%|███████▎  | 11/15 [00:01<00:00,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0034:  80%|████████  | 12/15 [00:02<00:00,  5.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0034:  87%|████████▋ | 13/15 [00:02<00:00,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0034:  93%|█████████▎| 14/15 [00:02<00:00,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0034: 100%|██████████| 15/15 [00:02<00:00,  5.85it/s]
Extracting features for accident_0035:   0%|          | 0/8 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0035:  12%|█▎        | 1/8 [00:00<00:01,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0035:  25%|██▌       | 2/8 [00:00<00:00,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0035:  38%|███▊      | 3/8 [00:00<00:00,  6.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0035:  50%|█████     | 4/8 [00:00<00:00,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0035:  62%|██████▎   | 5/8 [00:00<00:00,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0035:  75%|███████▌  | 6/8 [00:00<00:00,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0035:  88%|████████▊ | 7/8 [00:01<00:00,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0035: 100%|██████████| 8/8 [00:01<00:00,  5.82it/s]
Extracting features for accident_0036:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0036:   8%|▊         | 1/13 [00:00<00:02,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0036:  15%|█▌        | 2/13 [00:00<00:02,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0036:  23%|██▎       | 3/13 [00:00<00:02,  4.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0036:  31%|███       | 4/13 [00:00<00:01,  5.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0036:  38%|███▊      | 5/13 [00:00<00:01,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0036:  46%|████▌     | 6/13 [00:01<00:01,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0036:  54%|█████▍    | 7/13 [00:01<00:01,  5.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0036:  62%|██████▏   | 8/13 [00:01<00:00,  5.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0036:  69%|██████▉   | 9/13 [00:01<00:00,  5.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0036:  77%|███████▋  | 10/13 [00:01<00:00,  5.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0036:  85%|████████▍ | 11/13 [00:01<00:00,  6.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0036:  92%|█████████▏| 12/13 [00:02<00:00,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0036: 100%|██████████| 13/13 [00:02<00:00,  5.70it/s]
Extracting features for accident_0037:   0%|          | 0/10 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0037:  10%|█         | 1/10 [00:00<00:01,  6.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0037:  20%|██        | 2/10 [00:00<00:01,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0037:  30%|███       | 3/10 [00:00<00:01,  6.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0037:  40%|████      | 4/10 [00:00<00:00,  6.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0037:  50%|█████     | 5/10 [00:00<00:00,  6.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0037:  60%|██████    | 6/10 [00:00<00:00,  6.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0037:  70%|███████   | 7/10 [00:01<00:00,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0037:  80%|████████  | 8/10 [00:01<00:00,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0037:  90%|█████████ | 9/10 [00:01<00:00,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0037: 100%|██████████| 10/10 [00:01<00:00,  5.92it/s]
Extracting features for accident_0038:   0%|          | 0/7 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0038:  14%|█▍        | 1/7 [00:00<00:00,  6.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0038:  29%|██▊       | 2/7 [00:00<00:00,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

Extracting features for accident_0038:  43%|████▎     | 3/7 [00:00<00:00,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

Extracting features for accident_0038:  57%|█████▋    | 4/7 [00:00<00:00,  4.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0038:  71%|███████▏  | 5/7 [00:01<00:00,  4.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for accident_0038:  86%|████████▌ | 6/7 [00:01<00:00,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0038: 100%|██████████| 7/7 [00:01<00:00,  4.57it/s]
Extracting features for accident_0039:   0%|          | 0/6 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

Extracting features for accident_0039:  17%|█▋        | 1/6 [00:00<00:01,  4.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for accident_0039:  33%|███▎      | 2/6 [00:00<00:01,  3.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0039:  50%|█████     | 3/6 [00:00<00:00,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

Extracting features for accident_0039:  67%|██████▋   | 4/6 [00:01<00:00,  3.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step

Extracting features for accident_0039:  83%|████████▎ | 5/6 [00:01<00:00,  3.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

Extracting features for accident_0039: 100%|██████████| 6/6 [00:01<00:00,  3.50it/s]
Extracting features for accident_004:   0%|          | 0/22 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_004:   5%|▍         | 1/22 [00:00<00:05,  4.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_004:   9%|▉         | 2/22 [00:00<00:05,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_004:  14%|█▎        | 3/22 [00:00<00:04,  3.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_004:  18%|█▊        | 4/22 [00:00<00:04,  4.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_004:  23%|██▎       | 5/22 [00:01<00:04,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_004:  27%|██▋       | 6/22 [00:01<00:03,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_004:  32%|███▏      | 7/22 [00:01<00:03,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_004:  36%|███▋      | 8/22 [00:01<00:02,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_004:  41%|████      | 9/22 [00:01<00:02,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_004:  45%|████▌     | 10/22 [00:02<00:02,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_004:  50%|█████     | 11/22 [00:02<00:01,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_004:  55%|█████▍    | 12/22 [00:02<00:01,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_004:  59%|█████▉    | 13/22 [00:02<00:01,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_004:  64%|██████▎   | 14/22 [00:02<00:01,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_004:  68%|██████▊   | 15/22 [00:02<00:01,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_004:  73%|███████▎  | 16/22 [00:03<00:01,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_004:  77%|███████▋  | 17/22 [00:03<00:00,  5.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_004:  82%|████████▏ | 18/22 [00:03<00:00,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_004:  86%|████████▋ | 19/22 [00:03<00:00,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_004:  91%|█████████ | 20/22 [00:03<00:00,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_004:  95%|█████████▌| 21/22 [00:04<00:00,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_004: 100%|██████████| 22/22 [00:04<00:00,  5.23it/s]
Extracting features for accident_0040:   0%|          | 0/11 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0040:   9%|▉         | 1/11 [00:00<00:01,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0040:  18%|█▊        | 2/11 [00:00<00:01,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0040:  27%|██▋       | 3/11 [00:00<00:01,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0040:  36%|███▋      | 4/11 [00:00<00:01,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0040:  45%|████▌     | 5/11 [00:00<00:00,  6.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0040:  55%|█████▍    | 6/11 [00:00<00:00,  6.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0040:  64%|██████▎   | 7/11 [00:01<00:00,  6.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0040:  73%|███████▎  | 8/11 [00:01<00:00,  6.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0040:  82%|████████▏ | 9/11 [00:01<00:00,  6.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0040:  91%|█████████ | 10/11 [00:01<00:00,  6.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0040: 100%|██████████| 11/11 [00:01<00:00,  6.06it/s]
Extracting features for accident_0041:   0%|          | 0/8 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0041:  12%|█▎        | 1/8 [00:00<00:01,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0041:  25%|██▌       | 2/8 [00:00<00:01,  5.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0041:  38%|███▊      | 3/8 [00:00<00:00,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0041:  50%|█████     | 4/8 [00:00<00:00,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0041:  62%|██████▎   | 5/8 [00:00<00:00,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0041:  75%|███████▌  | 6/8 [00:01<00:00,  6.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0041:  88%|████████▊ | 7/8 [00:01<00:00,  6.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0041: 100%|██████████| 8/8 [00:01<00:00,  6.06it/s]
Extracting features for accident_0042:   0%|          | 0/8 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0042:  12%|█▎        | 1/8 [00:00<00:01,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0042:  25%|██▌       | 2/8 [00:00<00:01,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0042:  38%|███▊      | 3/8 [00:00<00:00,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0042:  50%|█████     | 4/8 [00:00<00:00,  4.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0042:  62%|██████▎   | 5/8 [00:00<00:00,  5.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0042:  75%|███████▌  | 6/8 [00:01<00:00,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

Extracting features for accident_0042:  88%|████████▊ | 7/8 [00:01<00:00,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0042: 100%|██████████| 8/8 [00:01<00:00,  5.43it/s]
Extracting features for accident_0043:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0043:   8%|▊         | 1/13 [00:00<00:02,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0043:  15%|█▌        | 2/13 [00:00<00:01,  6.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0043:  23%|██▎       | 3/13 [00:00<00:01,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_0043:  31%|███       | 4/13 [00:00<00:01,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

Extracting features for accident_0043:  38%|███▊      | 5/13 [00:01<00:01,  4.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0043:  46%|████▌     | 6/13 [00:01<00:01,  4.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

Extracting features for accident_0043:  54%|█████▍    | 7/13 [00:01<00:01,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step

Extracting features for accident_0043:  62%|██████▏   | 8/13 [00:01<00:01,  4.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for accident_0043:  69%|██████▉   | 9/13 [00:01<00:00,  4.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

Extracting features for accident_0043:  77%|███████▋  | 10/13 [00:02<00:00,  4.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

Extracting features for accident_0043:  85%|████████▍ | 11/13 [00:02<00:00,  4.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

Extracting features for accident_0043:  92%|█████████▏| 12/13 [00:02<00:00,  4.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step

Extracting features for accident_0043: 100%|██████████| 13/13 [00:02<00:00,  4.40it/s]
Extracting features for accident_0044:   0%|          | 0/11 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step

Extracting features for accident_0044:   9%|▉         | 1/11 [00:00<00:04,  2.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step

Extracting features for accident_0044:  18%|█▊        | 2/11 [00:00<00:03,  2.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step

Extracting features for accident_0044:  27%|██▋       | 3/11 [00:01<00:02,  2.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step

Extracting features for accident_0044:  36%|███▋      | 4/11 [00:01<00:02,  2.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step

Extracting features for accident_0044:  45%|████▌     | 5/11 [00:01<00:02,  2.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step

Extracting features for accident_0044:  55%|█████▍    | 6/11 [00:02<00:01,  2.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step

Extracting features for accident_0044:  64%|██████▎   | 7/11 [00:02<00:01,  2.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step

Extracting features for accident_0044:  73%|███████▎  | 8/11 [00:03<00:01,  2.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step

Extracting features for accident_0044:  82%|████████▏ | 9/11 [00:03<00:00,  2.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 263ms/step

Extracting features for accident_0044:  91%|█████████ | 10/11 [00:03<00:00,  2.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step

Extracting features for accident_0044: 100%|██████████| 11/11 [00:04<00:00,  2.57it/s]
Extracting features for accident_0045:   0%|          | 0/9 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 327ms/step

Extracting features for accident_0045:  11%|█         | 1/9 [00:00<00:04,  1.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

Extracting features for accident_0045:  22%|██▏       | 2/9 [00:01<00:03,  1.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step

Extracting features for accident_0045:  33%|███▎      | 3/9 [00:01<00:02,  2.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

Extracting features for accident_0045:  44%|████▍     | 4/9 [00:01<00:01,  2.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_0045:  56%|█████▌    | 5/9 [00:01<00:01,  3.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0045:  67%|██████▋   | 6/9 [00:02<00:00,  3.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0045:  78%|███████▊  | 7/9 [00:02<00:00,  4.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

Extracting features for accident_0045:  89%|████████▉ | 8/9 [00:02<00:00,  4.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0045: 100%|██████████| 9/9 [00:02<00:00,  3.39it/s]
Extracting features for accident_0046:   0%|          | 0/5 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0046:  20%|██        | 1/5 [00:00<00:00,  5.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0046:  40%|████      | 2/5 [00:00<00:00,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0046:  60%|██████    | 3/5 [00:00<00:00,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0046:  80%|████████  | 4/5 [00:00<00:00,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0046: 100%|██████████| 5/5 [00:00<00:00,  5.20it/s]
Extracting features for accident_0047:   0%|          | 0/9 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0047:  11%|█         | 1/9 [00:00<00:01,  5.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0047:  22%|██▏       | 2/9 [00:00<00:01,  6.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0047:  33%|███▎      | 3/9 [00:00<00:00,  6.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0047:  44%|████▍     | 4/9 [00:00<00:00,  6.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0047:  56%|█████▌    | 5/9 [00:00<00:00,  6.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0047:  67%|██████▋   | 6/9 [00:01<00:00,  5.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0047:  78%|███████▊  | 7/9 [00:01<00:00,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0047:  89%|████████▉ | 8/9 [00:01<00:00,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0047: 100%|██████████| 9/9 [00:01<00:00,  5.97it/s]
Extracting features for accident_0048:   0%|          | 0/12 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0048:   8%|▊         | 1/12 [00:00<00:01,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0048:  17%|█▋        | 2/12 [00:00<00:01,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0048:  25%|██▌       | 3/12 [00:00<00:01,  5.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0048:  33%|███▎      | 4/12 [00:00<00:01,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0048:  42%|████▏     | 5/12 [00:00<00:01,  5.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0048:  50%|█████     | 6/12 [00:01<00:01,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_0048:  58%|█████▊    | 7/12 [00:01<00:00,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

Extracting features for accident_0048:  67%|██████▋   | 8/12 [00:01<00:00,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0048:  75%|███████▌  | 9/12 [00:01<00:00,  5.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0048:  83%|████████▎ | 10/12 [00:01<00:00,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0048:  92%|█████████▏| 11/12 [00:02<00:00,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0048: 100%|██████████| 12/12 [00:02<00:00,  5.50it/s]
Extracting features for accident_0049:   0%|          | 0/7 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0049:  14%|█▍        | 1/7 [00:00<00:01,  5.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0049:  29%|██▊       | 2/7 [00:00<00:00,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0049:  43%|████▎     | 3/7 [00:00<00:00,  5.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0049:  57%|█████▋    | 4/7 [00:00<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0049:  71%|███████▏  | 5/7 [00:00<00:00,  5.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0049:  86%|████████▌ | 6/7 [00:01<00:00,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0049: 100%|██████████| 7/7 [00:01<00:00,  5.76it/s]
Extracting features for accident_005:   0%|          | 0/27 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for accident_005:   4%|▎         | 1/27 [00:00<00:06,  3.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_005:   7%|▋         | 2/27 [00:00<00:05,  4.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_005:  11%|█         | 3/27 [00:00<00:04,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_005:  15%|█▍        | 4/27 [00:00<00:04,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_005:  19%|█▊        | 5/27 [00:00<00:03,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_005:  22%|██▏       | 6/27 [00:01<00:04,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_005:  26%|██▌       | 7/27 [00:01<00:03,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_005:  30%|██▉       | 8/27 [00:01<00:03,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_005:  33%|███▎      | 9/27 [00:01<00:03,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step

Extracting features for accident_005:  37%|███▋      | 10/27 [00:01<00:02,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_005:  41%|████      | 11/27 [00:02<00:02,  5.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

Extracting features for accident_005:  44%|████▍     | 12/27 [00:02<00:02,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_005:  48%|████▊     | 13/27 [00:02<00:02,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_005:  52%|█████▏    | 14/27 [00:02<00:02,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_005:  56%|█████▌    | 15/27 [00:02<00:02,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

Extracting features for accident_005:  59%|█████▉    | 16/27 [00:02<00:02,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step

Extracting features for accident_005:  63%|██████▎   | 17/27 [00:03<00:02,  4.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for accident_005:  67%|██████▋   | 18/27 [00:03<00:02,  4.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_005:  70%|███████   | 19/27 [00:03<00:01,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for accident_005:  74%|███████▍  | 20/27 [00:03<00:01,  4.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step

Extracting features for accident_005:  78%|███████▊  | 21/27 [00:04<00:01,  4.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_005:  81%|████████▏ | 22/27 [00:04<00:01,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_005:  85%|████████▌ | 23/27 [00:04<00:00,  4.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_005:  89%|████████▉ | 24/27 [00:05<00:00,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for accident_005:  93%|█████████▎| 25/27 [00:05<00:00,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step

Extracting features for accident_005:  96%|█████████▋| 26/27 [00:05<00:00,  3.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for accident_005: 100%|██████████| 27/27 [00:05<00:00,  4.67it/s]
Extracting features for accident_0050:   0%|          | 0/12 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

Extracting features for accident_0050:   8%|▊         | 1/12 [00:00<00:02,  3.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for accident_0050:  17%|█▋        | 2/12 [00:00<00:02,  3.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0050:  25%|██▌       | 3/12 [00:00<00:02,  3.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0050:  33%|███▎      | 4/12 [00:01<00:02,  3.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for accident_0050:  42%|████▏     | 5/12 [00:01<00:01,  3.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

Extracting features for accident_0050:  50%|█████     | 6/12 [00:01<00:01,  3.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0050:  58%|█████▊    | 7/12 [00:01<00:01,  4.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0050:  67%|██████▋   | 8/12 [00:01<00:00,  4.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0050:  75%|███████▌  | 9/12 [00:02<00:00,  5.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0050:  83%|████████▎ | 10/12 [00:02<00:00,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0050:  92%|█████████▏| 11/12 [00:02<00:00,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0050: 100%|██████████| 12/12 [00:02<00:00,  4.64it/s]
Extracting features for accident_0051:   0%|          | 0/14 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0051:   7%|▋         | 1/14 [00:00<00:02,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0051:  14%|█▍        | 2/14 [00:00<00:02,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0051:  21%|██▏       | 3/14 [00:00<00:01,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0051:  29%|██▊       | 4/14 [00:00<00:01,  5.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0051:  36%|███▌      | 5/14 [00:00<00:01,  5.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0051:  43%|████▎     | 6/14 [00:01<00:01,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0051:  50%|█████     | 7/14 [00:01<00:01,  5.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0051:  57%|█████▋    | 8/14 [00:01<00:01,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0051:  64%|██████▍   | 9/14 [00:01<00:00,  5.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0051:  71%|███████▏  | 10/14 [00:01<00:00,  4.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0051:  79%|███████▊  | 11/14 [00:02<00:00,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0051:  86%|████████▌ | 12/14 [00:02<00:00,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for accident_0051:  93%|█████████▎| 13/14 [00:02<00:00,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_0051: 100%|██████████| 14/14 [00:02<00:00,  5.45it/s]
Extracting features for accident_0052:   0%|          | 0/8 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0052:  12%|█▎        | 1/8 [00:00<00:01,  4.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0052:  25%|██▌       | 2/8 [00:00<00:01,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0052:  38%|███▊      | 3/8 [00:00<00:00,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0052:  50%|█████     | 4/8 [00:00<00:00,  5.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0052:  62%|██████▎   | 5/8 [00:00<00:00,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0052:  75%|███████▌  | 6/8 [00:01<00:00,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0052:  88%|████████▊ | 7/8 [00:01<00:00,  5.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0052: 100%|██████████| 8/8 [00:01<00:00,  5.51it/s]
Extracting features for accident_0053:   0%|          | 0/10 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0053:  10%|█         | 1/10 [00:00<00:01,  5.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_0053:  20%|██        | 2/10 [00:00<00:01,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0053:  30%|███       | 3/10 [00:00<00:01,  5.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0053:  40%|████      | 4/10 [00:00<00:01,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0053:  50%|█████     | 5/10 [00:00<00:00,  5.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0053:  60%|██████    | 6/10 [00:01<00:00,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0053:  70%|███████   | 7/10 [00:01<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0053:  80%|████████  | 8/10 [00:01<00:00,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0053:  90%|█████████ | 9/10 [00:01<00:00,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0053: 100%|██████████| 10/10 [00:01<00:00,  5.58it/s]
Extracting features for accident_0054:   0%|          | 0/12 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0054:   8%|▊         | 1/12 [00:00<00:01,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0054:  17%|█▋        | 2/12 [00:00<00:01,  5.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0054:  25%|██▌       | 3/12 [00:00<00:01,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0054:  33%|███▎      | 4/12 [00:00<00:01,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0054:  42%|████▏     | 5/12 [00:00<00:01,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0054:  50%|█████     | 6/12 [00:01<00:01,  5.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0054:  58%|█████▊    | 7/12 [00:01<00:00,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0054:  67%|██████▋   | 8/12 [00:01<00:00,  5.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0054:  75%|███████▌  | 9/12 [00:01<00:00,  6.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0054:  83%|████████▎ | 10/12 [00:01<00:00,  5.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0054:  92%|█████████▏| 11/12 [00:01<00:00,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0054: 100%|██████████| 12/12 [00:02<00:00,  5.71it/s]
Extracting features for accident_0055:   0%|          | 0/12 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0055:   8%|▊         | 1/12 [00:00<00:02,  4.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0055:  17%|█▋        | 2/12 [00:00<00:01,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0055:  25%|██▌       | 3/12 [00:00<00:01,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0055:  33%|███▎      | 4/12 [00:00<00:01,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0055:  42%|████▏     | 5/12 [00:00<00:01,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for accident_0055:  50%|█████     | 6/12 [00:01<00:01,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for accident_0055:  58%|█████▊    | 7/12 [00:01<00:01,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for accident_0055:  67%|██████▋   | 8/12 [00:01<00:00,  4.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0055:  75%|███████▌  | 9/12 [00:01<00:00,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0055:  83%|████████▎ | 10/12 [00:02<00:00,  4.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

Extracting features for accident_0055:  92%|█████████▏| 11/12 [00:02<00:00,  4.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for accident_0055: 100%|██████████| 12/12 [00:02<00:00,  4.59it/s]
Extracting features for accident_0056:   0%|          | 0/17 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step

Extracting features for accident_0056:   6%|▌         | 1/17 [00:00<00:04,  3.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for accident_0056:  12%|█▏        | 2/17 [00:00<00:05,  2.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_0056:  18%|█▊        | 3/17 [00:00<00:04,  3.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step

Extracting features for accident_0056:  24%|██▎       | 4/17 [00:01<00:04,  2.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_0056:  29%|██▉       | 5/17 [00:01<00:03,  3.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step

Extracting features for accident_0056:  35%|███▌      | 6/17 [00:01<00:03,  3.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for accident_0056:  41%|████      | 7/17 [00:02<00:02,  3.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

Extracting features for accident_0056:  47%|████▋     | 8/17 [00:02<00:03,  2.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0056:  53%|█████▎    | 9/17 [00:02<00:02,  3.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0056:  59%|█████▉    | 10/17 [00:02<00:01,  3.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0056:  65%|██████▍   | 11/17 [00:03<00:01,  4.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0056:  71%|███████   | 12/17 [00:03<00:01,  4.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0056:  76%|███████▋  | 13/17 [00:03<00:00,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_0056:  82%|████████▏ | 14/17 [00:03<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0056:  88%|████████▊ | 15/17 [00:03<00:00,  4.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0056:  94%|█████████▍| 16/17 [00:04<00:00,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0056: 100%|██████████| 17/17 [00:04<00:00,  3.98it/s]
Extracting features for accident_0057:   0%|          | 0/11 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for accident_0057:   9%|▉         | 1/11 [00:00<00:01,  5.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0057:  18%|█▊        | 2/11 [00:00<00:01,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0057:  27%|██▋       | 3/11 [00:00<00:01,  5.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0057:  36%|███▋      | 4/11 [00:00<00:01,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_0057:  45%|████▌     | 5/11 [00:00<00:01,  5.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0057:  55%|█████▍    | 6/11 [00:01<00:00,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0057:  64%|██████▎   | 7/11 [00:01<00:00,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0057:  73%|███████▎  | 8/11 [00:01<00:00,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0057:  82%|████████▏ | 9/11 [00:01<00:00,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_0057:  91%|█████████ | 10/11 [00:01<00:00,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0057: 100%|██████████| 11/11 [00:02<00:00,  5.19it/s]
Extracting features for accident_0058:   0%|          | 0/11 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_0058:   9%|▉         | 1/11 [00:00<00:01,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0058:  18%|█▊        | 2/11 [00:00<00:01,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0058:  27%|██▋       | 3/11 [00:00<00:01,  5.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0058:  36%|███▋      | 4/11 [00:00<00:01,  5.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0058:  45%|████▌     | 5/11 [00:00<00:01,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0058:  55%|█████▍    | 6/11 [00:01<00:00,  5.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0058:  64%|██████▎   | 7/11 [00:01<00:00,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0058:  73%|███████▎  | 8/11 [00:01<00:00,  5.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0058:  82%|████████▏ | 9/11 [00:01<00:00,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0058:  91%|█████████ | 10/11 [00:01<00:00,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0058: 100%|██████████| 11/11 [00:01<00:00,  5.51it/s]
Extracting features for accident_0059:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for accident_0059:   8%|▊         | 1/13 [00:00<00:02,  5.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0059:  15%|█▌        | 2/13 [00:00<00:01,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0059:  23%|██▎       | 3/13 [00:00<00:01,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0059:  31%|███       | 4/13 [00:00<00:01,  5.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0059:  38%|███▊      | 5/13 [00:00<00:01,  4.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0059:  46%|████▌     | 6/13 [00:01<00:01,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0059:  54%|█████▍    | 7/13 [00:01<00:01,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0059:  62%|██████▏   | 8/13 [00:01<00:00,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0059:  69%|██████▉   | 9/13 [00:01<00:00,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0059:  77%|███████▋  | 10/13 [00:01<00:00,  5.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_0059:  85%|████████▍ | 11/13 [00:02<00:00,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step

Extracting features for accident_0059:  92%|█████████▏| 12/13 [00:02<00:00,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0059: 100%|██████████| 13/13 [00:02<00:00,  5.35it/s]
Extracting features for accident_006:   0%|          | 0/19 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_006:   5%|▌         | 1/19 [00:00<00:03,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_006:  11%|█         | 2/19 [00:00<00:03,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_006:  16%|█▌        | 3/19 [00:00<00:02,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_006:  21%|██        | 4/19 [00:00<00:02,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for accident_006:  26%|██▋       | 5/19 [00:00<00:02,  5.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_006:  32%|███▏      | 6/19 [00:01<00:02,  5.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_006:  37%|███▋      | 7/19 [00:01<00:02,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_006:  42%|████▏     | 8/19 [00:01<00:01,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_006:  47%|████▋     | 9/19 [00:01<00:01,  5.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step

Extracting features for accident_006:  53%|█████▎    | 10/19 [00:01<00:01,  5.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_006:  58%|█████▊    | 11/19 [00:02<00:01,  4.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step

Extracting features for accident_006:  63%|██████▎   | 12/19 [00:02<00:01,  4.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

Extracting features for accident_006:  68%|██████▊   | 13/19 [00:02<00:01,  4.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_006:  74%|███████▎  | 14/19 [00:02<00:01,  4.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step

Extracting features for accident_006:  79%|███████▉  | 15/19 [00:03<00:01,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for accident_006:  84%|████████▍ | 16/19 [00:03<00:00,  3.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_006:  89%|████████▉ | 17/19 [00:03<00:00,  3.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_006:  95%|█████████▍| 18/19 [00:03<00:00,  3.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_006: 100%|██████████| 19/19 [00:04<00:00,  4.50it/s]
Extracting features for accident_0060:   0%|          | 0/14 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for accident_0060:   7%|▋         | 1/14 [00:00<00:03,  3.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for accident_0060:  14%|█▍        | 2/14 [00:00<00:03,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

Extracting features for accident_0060:  21%|██▏       | 3/14 [00:00<00:03,  3.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step

Extracting features for accident_0060:  29%|██▊       | 4/14 [00:01<00:02,  3.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

Extracting features for accident_0060:  36%|███▌      | 5/14 [00:01<00:02,  3.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_0060:  43%|████▎     | 6/14 [00:01<00:02,  3.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0060:  50%|█████     | 7/14 [00:01<00:01,  4.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_0060:  57%|█████▋    | 8/14 [00:02<00:01,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0060:  64%|██████▍   | 9/14 [00:02<00:01,  4.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0060:  71%|███████▏  | 10/14 [00:02<00:00,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_0060:  79%|███████▊  | 11/14 [00:02<00:00,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0060:  86%|████████▌ | 12/14 [00:02<00:00,  5.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0060:  93%|█████████▎| 13/14 [00:02<00:00,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0060: 100%|██████████| 14/14 [00:03<00:00,  4.47it/s]
Extracting features for accident_0061:   0%|          | 0/6 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0061:  17%|█▋        | 1/6 [00:00<00:00,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0061:  33%|███▎      | 2/6 [00:00<00:00,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0061:  50%|█████     | 3/6 [00:00<00:00,  5.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0061:  67%|██████▋   | 4/6 [00:00<00:00,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0061:  83%|████████▎ | 5/6 [00:00<00:00,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0061: 100%|██████████| 6/6 [00:01<00:00,  5.62it/s]
Extracting features for accident_0062:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0062:   8%|▊         | 1/13 [00:00<00:02,  4.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0062:  15%|█▌        | 2/13 [00:00<00:02,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0062:  23%|██▎       | 3/13 [00:00<00:01,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0062:  31%|███       | 4/13 [00:00<00:01,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_0062:  38%|███▊      | 5/13 [00:00<00:01,  5.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0062:  46%|████▌     | 6/13 [00:01<00:01,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0062:  54%|█████▍    | 7/13 [00:01<00:01,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0062:  62%|██████▏   | 8/13 [00:01<00:00,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0062:  69%|██████▉   | 9/13 [00:01<00:00,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0062:  77%|███████▋  | 10/13 [00:01<00:00,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for accident_0062:  85%|████████▍ | 11/13 [00:02<00:00,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0062:  92%|█████████▏| 12/13 [00:02<00:00,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0062: 100%|██████████| 13/13 [00:02<00:00,  5.53it/s]
Extracting features for accident_0063:   0%|          | 0/14 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0063:   7%|▋         | 1/14 [00:00<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0063:  14%|█▍        | 2/14 [00:00<00:02,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0063:  21%|██▏       | 3/14 [00:00<00:01,  5.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_0063:  29%|██▊       | 4/14 [00:00<00:01,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0063:  36%|███▌      | 5/14 [00:00<00:01,  5.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0063:  43%|████▎     | 6/14 [00:01<00:01,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0063:  50%|█████     | 7/14 [00:01<00:01,  5.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for accident_0063:  57%|█████▋    | 8/14 [00:01<00:01,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_0063:  64%|██████▍   | 9/14 [00:01<00:00,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

Extracting features for accident_0063:  71%|███████▏  | 10/14 [00:01<00:00,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0063:  79%|███████▊  | 11/14 [00:01<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0063:  86%|████████▌ | 12/14 [00:02<00:00,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0063:  93%|█████████▎| 13/14 [00:02<00:00,  5.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0063: 100%|██████████| 14/14 [00:02<00:00,  5.45it/s]
Extracting features for accident_0064:   0%|          | 0/9 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for accident_0064:  11%|█         | 1/9 [00:00<00:01,  4.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for accident_0064:  22%|██▏       | 2/9 [00:00<00:01,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0064:  33%|███▎      | 3/9 [00:00<00:01,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0064:  44%|████▍     | 4/9 [00:00<00:00,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0064:  56%|█████▌    | 5/9 [00:00<00:00,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0064:  67%|██████▋   | 6/9 [00:01<00:00,  5.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

Extracting features for accident_0064:  78%|███████▊  | 7/9 [00:01<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0064:  89%|████████▉ | 8/9 [00:01<00:00,  5.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0064: 100%|██████████| 9/9 [00:01<00:00,  5.70it/s]
Extracting features for accident_0065:   0%|          | 0/15 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0065:   7%|▋         | 1/15 [00:00<00:02,  5.60it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0065:  13%|█▎        | 2/15 [00:00<00:02,  5.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0065:  20%|██        | 3/15 [00:00<00:02,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_0065:  27%|██▋       | 4/15 [00:00<00:01,  5.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for accident_0065:  33%|███▎      | 5/15 [00:00<00:01,  6.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_0065:  40%|████      | 6/15 [00:01<00:01,  5.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for accident_0065:  47%|████▋     | 7/15 [00:01<00:01,  4.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step

Extracting features for accident_0065:  53%|█████▎    | 8/15 [00:01<00:01,  3.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for accident_0065:  60%|██████    | 9/15 [00:01<00:01,  3.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for accident_0065:  67%|██████▋   | 10/15 [00:02<00:01,  3.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for accident_0065:  73%|███████▎  | 11/15 [00:02<00:01,  3.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step

Extracting features for accident_0065:  80%|████████  | 12/15 [00:02<00:00,  3.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0065:  87%|████████▋ | 13/15 [00:03<00:00,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0065:  93%|█████████▎| 14/15 [00:03<00:00,  3.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for accident_0065: 100%|██████████| 15/15 [00:03<00:00,  4.10it/s]
Extracting features for accident_0066:   0%|          | 0/14 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step

Extracting features for accident_0066:   7%|▋         | 1/14 [00:00<00:03,  3.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

Extracting features for accident_0066:  14%|█▍        | 2/14 [00:00<00:03,  3.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for accident_0066:  21%|██▏       | 3/14 [00:00<00:02,  3.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step

Extracting features for accident_0066:  29%|██▊       | 4/14 [00:01<00:03,  3.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for accident_0066:  36%|███▌      | 5/14 [00:01<00:02,  3.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0066:  43%|████▎     | 6/14 [00:01<00:02,  3.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0066:  50%|█████     | 7/14 [00:01<00:01,  4.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0066:  57%|█████▋    | 8/14 [00:02<00:01,  4.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_0066:  64%|██████▍   | 9/14 [00:02<00:01,  4.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_0066:  71%|███████▏  | 10/14 [00:02<00:00,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0066:  79%|███████▊  | 11/14 [00:02<00:00,  5.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0066:  86%|████████▌ | 12/14 [00:02<00:00,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_0066:  93%|█████████▎| 13/14 [00:02<00:00,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_0066: 100%|██████████| 14/14 [00:03<00:00,  4.55it/s]
Extracting features for accident_0067:   0%|          | 0/12 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_0067:   8%|▊         | 1/12 [00:00<00:01,  5.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0067:  17%|█▋        | 2/12 [00:00<00:01,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_0067:  25%|██▌       | 3/12 [00:00<00:01,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_0067:  33%|███▎      | 4/12 [00:00<00:01,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_0067:  42%|████▏     | 5/12 [00:00<00:01,  5.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_0067:  50%|█████     | 6/12 [00:01<00:01,  4.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for accident_0067:  58%|█████▊    | 7/12 [00:01<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_0067:  67%|██████▋   | 8/12 [00:01<00:00,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_0067:  75%|███████▌  | 9/12 [00:01<00:00,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0067:  83%|████████▎ | 10/12 [00:01<00:00,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_0067:  92%|█████████▏| 11/12 [00:02<00:00,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_0067: 100%|██████████| 12/12 [00:02<00:00,  5.34it/s]
Extracting features for accident_007:   0%|          | 0/25 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_007:   4%|▍         | 1/25 [00:00<00:04,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_007:   8%|▊         | 2/25 [00:00<00:04,  5.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_007:  12%|█▏        | 3/25 [00:00<00:03,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_007:  16%|█▌        | 4/25 [00:00<00:03,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_007:  20%|██        | 5/25 [00:00<00:03,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for accident_007:  24%|██▍       | 6/25 [00:01<00:03,  5.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_007:  28%|██▊       | 7/25 [00:01<00:03,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_007:  32%|███▏      | 8/25 [00:01<00:03,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_007:  36%|███▌      | 9/25 [00:01<00:02,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_007:  40%|████      | 10/25 [00:01<00:02,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_007:  44%|████▍     | 11/25 [00:02<00:02,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_007:  48%|████▊     | 12/25 [00:02<00:02,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_007:  52%|█████▏    | 13/25 [00:02<00:02,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_007:  56%|█████▌    | 14/25 [00:02<00:02,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for accident_007:  60%|██████    | 15/25 [00:02<00:01,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_007:  64%|██████▍   | 16/25 [00:02<00:01,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for accident_007:  68%|██████▊   | 17/25 [00:03<00:01,  5.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_007:  72%|███████▏  | 18/25 [00:03<00:01,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_007:  76%|███████▌  | 19/25 [00:03<00:01,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_007:  80%|████████  | 20/25 [00:03<00:00,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for accident_007:  84%|████████▍ | 21/25 [00:03<00:00,  5.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for accident_007:  88%|████████▊ | 22/25 [00:04<00:00,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for accident_007:  92%|█████████▏| 23/25 [00:04<00:00,  4.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_007:  96%|█████████▌| 24/25 [00:04<00:00,  4.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_007: 100%|██████████| 25/25 [00:04<00:00,  5.32it/s]
Extracting features for accident_008:   0%|          | 0/21 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for accident_008:   5%|▍         | 1/21 [00:00<00:03,  5.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_008:  10%|▉         | 2/21 [00:00<00:03,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for accident_008:  14%|█▍        | 3/21 [00:00<00:03,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for accident_008:  19%|█▉        | 4/21 [00:00<00:03,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_008:  24%|██▍       | 5/21 [00:00<00:03,  5.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_008:  29%|██▊       | 6/21 [00:01<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_008:  33%|███▎      | 7/21 [00:01<00:02,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for accident_008:  38%|███▊      | 8/21 [00:01<00:02,  4.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

Extracting features for accident_008:  43%|████▎     | 9/21 [00:01<00:02,  4.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for accident_008:  48%|████▊     | 10/21 [00:02<00:02,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

Extracting features for accident_008:  52%|█████▏    | 11/21 [00:02<00:02,  4.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for accident_008:  57%|█████▋    | 12/21 [00:02<00:02,  4.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step

Extracting features for accident_008:  62%|██████▏   | 13/21 [00:02<00:01,  4.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step

Extracting features for accident_008:  67%|██████▋   | 14/21 [00:03<00:02,  3.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for accident_008:  71%|███████▏  | 15/21 [00:03<00:01,  3.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

Extracting features for accident_008:  76%|███████▌  | 16/21 [00:03<00:01,  3.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step

Extracting features for accident_008:  81%|████████  | 17/21 [00:04<00:01,  3.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step

Extracting features for accident_008:  86%|████████▌ | 18/21 [00:04<00:01,  2.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step

Extracting features for accident_008:  90%|█████████ | 19/21 [00:04<00:00,  3.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

Extracting features for accident_008:  95%|█████████▌| 20/21 [00:05<00:00,  3.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for accident_008: 100%|██████████| 21/21 [00:05<00:00,  4.02it/s]
Extracting features for accident_009:   0%|          | 0/18 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_009:   6%|▌         | 1/18 [00:00<00:03,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_009:  11%|█         | 2/18 [00:00<00:02,  5.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_009:  17%|█▋        | 3/18 [00:00<00:02,  5.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_009:  22%|██▏       | 4/18 [00:00<00:02,  5.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_009:  28%|██▊       | 5/18 [00:00<00:02,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_009:  33%|███▎      | 6/18 [00:01<00:02,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_009:  39%|███▉      | 7/18 [00:01<00:02,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for accident_009:  44%|████▍     | 8/18 [00:01<00:02,  4.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for accident_009:  50%|█████     | 9/18 [00:01<00:01,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_009:  56%|█████▌    | 10/18 [00:01<00:01,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for accident_009:  61%|██████    | 11/18 [00:02<00:01,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_009:  67%|██████▋   | 12/18 [00:02<00:01,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for accident_009:  72%|███████▏  | 13/18 [00:02<00:00,  5.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for accident_009:  78%|███████▊  | 14/18 [00:02<00:00,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for accident_009:  83%|████████▎ | 15/18 [00:02<00:00,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for accident_009:  89%|████████▉ | 16/18 [00:02<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for accident_009:  94%|█████████▍| 17/18 [00:03<00:00,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for accident_009: 100%|██████████| 18/18 [00:03<00:00,  5.40it/s]
Extracting features for driving_000:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_000:  25%|██▌       | 1/4 [00:00<00:00,  4.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_000:  50%|█████     | 2/4 [00:00<00:00,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_000:  75%|███████▌  | 3/4 [00:00<00:00,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_000: 100%|██████████| 4/4 [00:00<00:00,  4.63it/s]
Extracting features for driving_001:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_001:  25%|██▌       | 1/4 [00:00<00:00,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_001:  50%|█████     | 2/4 [00:00<00:00,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_001:  75%|███████▌  | 3/4 [00:00<00:00,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Extracting features for driving_001: 100%|██████████| 4/4 [00:00<00:00,  4.71it/s]
Extracting features for driving_0010:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_0010:  25%|██▌       | 1/4 [00:00<00:00,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for driving_0010:  50%|█████     | 2/4 [00:00<00:00,  5.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_0010:  75%|███████▌  | 3/4 [00:00<00:00,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_0010: 100%|██████████| 4/4 [00:00<00:00,  5.16it/s]
Extracting features for driving_00100:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00100:  25%|██▌       | 1/4 [00:00<00:00,  4.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00100:  50%|█████     | 2/4 [00:00<00:00,  5.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00100:  75%|███████▌  | 3/4 [00:00<00:00,  4.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00100: 100%|██████████| 4/4 [00:00<00:00,  4.52it/s]
Extracting features for driving_00101:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00101:  25%|██▌       | 1/4 [00:00<00:00,  5.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00101:  50%|█████     | 2/4 [00:00<00:00,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00101:  75%|███████▌  | 3/4 [00:00<00:00,  5.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00101: 100%|██████████| 4/4 [00:00<00:00,  5.20it/s]
Extracting features for driving_00102:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00102:  25%|██▌       | 1/4 [00:00<00:00,  4.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00102:  50%|█████     | 2/4 [00:00<00:00,  4.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00102:  75%|███████▌  | 3/4 [00:00<00:00,  4.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00102: 100%|██████████| 4/4 [00:00<00:00,  4.58it/s]
Extracting features for driving_00103:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00103:  25%|██▌       | 1/4 [00:00<00:00,  5.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00103:  50%|█████     | 2/4 [00:00<00:00,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00103:  75%|███████▌  | 3/4 [00:00<00:00,  4.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00103: 100%|██████████| 4/4 [00:00<00:00,  4.61it/s]
Extracting features for driving_00104:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00104:   8%|▊         | 1/13 [00:00<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00104:  15%|█▌        | 2/13 [00:00<00:01,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

Extracting features for driving_00104:  23%|██▎       | 3/13 [00:00<00:01,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for driving_00104:  31%|███       | 4/13 [00:00<00:02,  4.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_00104:  38%|███▊      | 5/13 [00:01<00:01,  4.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step

Extracting features for driving_00104:  46%|████▌     | 6/13 [00:01<00:02,  3.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for driving_00104:  54%|█████▍    | 7/13 [00:01<00:01,  3.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

Extracting features for driving_00104:  62%|██████▏   | 8/13 [00:02<00:01,  2.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for driving_00104:  69%|██████▉   | 9/13 [00:02<00:01,  3.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for driving_00104:  77%|███████▋  | 10/13 [00:02<00:00,  3.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step

Extracting features for driving_00104:  85%|████████▍ | 11/13 [00:03<00:00,  2.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

Extracting features for driving_00104:  92%|█████████▏| 12/13 [00:03<00:00,  3.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for driving_00104: 100%|██████████| 13/13 [00:03<00:00,  3.50it/s]
Extracting features for driving_00105:   0%|          | 0/19 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_00105:   5%|▌         | 1/19 [00:00<00:04,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step

Extracting features for driving_00105:  11%|█         | 2/19 [00:00<00:04,  4.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00105:  16%|█▌        | 3/19 [00:00<00:03,  4.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00105:  21%|██        | 4/19 [00:00<00:02,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00105:  26%|██▋       | 5/19 [00:01<00:02,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00105:  32%|███▏      | 6/19 [00:01<00:02,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

Extracting features for driving_00105:  37%|███▋      | 7/19 [00:01<00:02,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00105:  42%|████▏     | 8/19 [00:01<00:02,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00105:  47%|████▋     | 9/19 [00:01<00:02,  4.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00105:  53%|█████▎    | 10/19 [00:02<00:01,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00105:  58%|█████▊    | 11/19 [00:02<00:01,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00105:  63%|██████▎   | 12/19 [00:02<00:01,  5.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00105:  68%|██████▊   | 13/19 [00:02<00:01,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00105:  74%|███████▎  | 14/19 [00:02<00:01,  4.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00105:  79%|███████▉  | 15/19 [00:03<00:00,  5.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00105:  84%|████████▍ | 16/19 [00:03<00:00,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00105:  89%|████████▉ | 17/19 [00:03<00:00,  5.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00105:  95%|█████████▍| 18/19 [00:03<00:00,  4.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00105: 100%|██████████| 19/19 [00:03<00:00,  4.93it/s]
Extracting features for driving_00106:   0%|          | 0/15 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00106:   7%|▋         | 1/15 [00:00<00:02,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00106:  13%|█▎        | 2/15 [00:00<00:02,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00106:  20%|██        | 3/15 [00:00<00:02,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_00106:  27%|██▋       | 4/15 [00:00<00:02,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00106:  33%|███▎      | 5/15 [00:00<00:01,  5.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00106:  40%|████      | 6/15 [00:01<00:01,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00106:  47%|████▋     | 7/15 [00:01<00:01,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00106:  53%|█████▎    | 8/15 [00:01<00:01,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00106:  60%|██████    | 9/15 [00:01<00:01,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00106:  67%|██████▋   | 10/15 [00:01<00:00,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00106:  73%|███████▎  | 11/15 [00:02<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00106:  80%|████████  | 12/15 [00:02<00:00,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00106:  87%|████████▋ | 13/15 [00:02<00:00,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00106:  93%|█████████▎| 14/15 [00:02<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_00106: 100%|██████████| 15/15 [00:02<00:00,  5.38it/s]
Extracting features for driving_00107:   0%|          | 0/19 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00107:   5%|▌         | 1/19 [00:00<00:03,  5.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00107:  11%|█         | 2/19 [00:00<00:03,  4.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00107:  16%|█▌        | 3/19 [00:00<00:03,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00107:  21%|██        | 4/19 [00:00<00:02,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00107:  26%|██▋       | 5/19 [00:00<00:02,  5.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00107:  32%|███▏      | 6/19 [00:01<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00107:  37%|███▋      | 7/19 [00:01<00:02,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00107:  42%|████▏     | 8/19 [00:01<00:02,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00107:  47%|████▋     | 9/19 [00:01<00:02,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00107:  53%|█████▎    | 10/19 [00:01<00:01,  5.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00107:  58%|█████▊    | 11/19 [00:02<00:01,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00107:  63%|██████▎   | 12/19 [00:02<00:01,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00107:  68%|██████▊   | 13/19 [00:02<00:01,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00107:  74%|███████▎  | 14/19 [00:02<00:00,  5.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00107:  79%|███████▉  | 15/19 [00:02<00:00,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00107:  84%|████████▍ | 16/19 [00:03<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00107:  89%|████████▉ | 17/19 [00:03<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00107:  95%|█████████▍| 18/19 [00:03<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00107: 100%|██████████| 19/19 [00:03<00:00,  5.13it/s]
Extracting features for driving_00108:   0%|          | 0/13 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_00108:   8%|▊         | 1/13 [00:00<00:03,  3.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_00108:  15%|█▌        | 2/13 [00:00<00:02,  3.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step

Extracting features for driving_00108:  23%|██▎       | 3/13 [00:00<00:02,  4.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for driving_00108:  31%|███       | 4/13 [00:00<00:02,  4.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for driving_00108:  38%|███▊      | 5/13 [00:01<00:01,  4.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for driving_00108:  46%|████▌     | 6/13 [00:01<00:01,  4.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step

Extracting features for driving_00108:  54%|█████▍    | 7/13 [00:01<00:01,  4.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step

Extracting features for driving_00108:  62%|██████▏   | 8/13 [00:01<00:01,  4.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for driving_00108:  69%|██████▉   | 9/13 [00:02<00:01,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for driving_00108:  77%|███████▋  | 10/13 [00:02<00:00,  3.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for driving_00108:  85%|████████▍ | 11/13 [00:02<00:00,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step

Extracting features for driving_00108:  92%|█████████▏| 12/13 [00:03<00:00,  3.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step

Extracting features for driving_00108: 100%|██████████| 13/13 [00:03<00:00,  3.98it/s]
Extracting features for driving_00109:   0%|          | 0/15 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

Extracting features for driving_00109:   7%|▋         | 1/15 [00:00<00:03,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step

Extracting features for driving_00109:  13%|█▎        | 2/15 [00:00<00:03,  3.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_00109:  20%|██        | 3/15 [00:00<00:03,  3.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for driving_00109:  27%|██▋       | 4/15 [00:01<00:02,  3.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00109:  33%|███▎      | 5/15 [00:01<00:02,  4.26it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00109:  40%|████      | 6/15 [00:01<00:01,  4.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00109:  47%|████▋     | 7/15 [00:01<00:01,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00109:  53%|█████▎    | 8/15 [00:01<00:01,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00109:  60%|██████    | 9/15 [00:01<00:01,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00109:  67%|██████▋   | 10/15 [00:02<00:00,  5.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00109:  73%|███████▎  | 11/15 [00:02<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00109:  80%|████████  | 12/15 [00:02<00:00,  5.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for driving_00109:  87%|████████▋ | 13/15 [00:02<00:00,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00109:  93%|█████████▎| 14/15 [00:02<00:00,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00109: 100%|██████████| 15/15 [00:03<00:00,  4.88it/s]
Extracting features for driving_0011:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for driving_0011:  25%|██▌       | 1/4 [00:00<00:00,  4.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_0011:  50%|█████     | 2/4 [00:00<00:00,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_0011:  75%|███████▌  | 3/4 [00:00<00:00,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_0011: 100%|██████████| 4/4 [00:00<00:00,  4.85it/s]
Extracting features for driving_00110:   0%|          | 0/22 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00110:   5%|▍         | 1/22 [00:00<00:03,  5.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00110:   9%|▉         | 2/22 [00:00<00:03,  5.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00110:  14%|█▎        | 3/22 [00:00<00:03,  5.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00110:  18%|█▊        | 4/22 [00:00<00:03,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00110:  23%|██▎       | 5/22 [00:00<00:03,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00110:  27%|██▋       | 6/22 [00:01<00:02,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00110:  32%|███▏      | 7/22 [00:01<00:02,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00110:  36%|███▋      | 8/22 [00:01<00:02,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00110:  41%|████      | 9/22 [00:01<00:02,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_00110:  45%|████▌     | 10/22 [00:01<00:02,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00110:  50%|█████     | 11/22 [00:02<00:02,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00110:  55%|█████▍    | 12/22 [00:02<00:01,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00110:  59%|█████▉    | 13/22 [00:02<00:01,  5.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00110:  64%|██████▎   | 14/22 [00:02<00:01,  5.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00110:  68%|██████▊   | 15/22 [00:02<00:01,  5.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

Extracting features for driving_00110:  73%|███████▎  | 16/22 [00:02<00:01,  5.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00110:  77%|███████▋  | 17/22 [00:03<00:00,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00110:  82%|████████▏ | 18/22 [00:03<00:00,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00110:  86%|████████▋ | 19/22 [00:03<00:00,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00110:  91%|█████████ | 20/22 [00:03<00:00,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_00110:  95%|█████████▌| 21/22 [00:03<00:00,  4.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00110: 100%|██████████| 22/22 [00:04<00:00,  5.37it/s]
Extracting features for driving_00111:   0%|          | 0/16 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00111:   6%|▋         | 1/16 [00:00<00:02,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00111:  12%|█▎        | 2/16 [00:00<00:02,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00111:  19%|█▉        | 3/16 [00:00<00:02,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00111:  25%|██▌       | 4/16 [00:00<00:02,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00111:  31%|███▏      | 5/16 [00:00<00:02,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00111:  38%|███▊      | 6/16 [00:01<00:01,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00111:  44%|████▍     | 7/16 [00:01<00:01,  5.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00111:  50%|█████     | 8/16 [00:01<00:01,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for driving_00111:  56%|█████▋    | 9/16 [00:01<00:01,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00111:  62%|██████▎   | 10/16 [00:01<00:01,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00111:  69%|██████▉   | 11/16 [00:02<00:00,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00111:  75%|███████▌  | 12/16 [00:02<00:00,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00111:  81%|████████▏ | 13/16 [00:02<00:00,  5.42it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00111:  88%|████████▊ | 14/16 [00:02<00:00,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00111:  94%|█████████▍| 15/16 [00:02<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00111: 100%|██████████| 16/16 [00:02<00:00,  5.48it/s]
Extracting features for driving_00112:   0%|          | 0/17 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_00112:   6%|▌         | 1/17 [00:00<00:04,  3.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for driving_00112:  12%|█▏        | 2/17 [00:00<00:03,  3.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

Extracting features for driving_00112:  18%|█▊        | 3/17 [00:00<00:03,  3.72it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for driving_00112:  24%|██▎       | 4/17 [00:01<00:03,  3.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

Extracting features for driving_00112:  29%|██▉       | 5/17 [00:01<00:03,  3.01it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for driving_00112:  35%|███▌      | 6/17 [00:01<00:03,  3.23it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step

Extracting features for driving_00112:  41%|████      | 7/17 [00:02<00:03,  2.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for driving_00112:  47%|████▋     | 8/17 [00:02<00:02,  3.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for driving_00112:  53%|█████▎    | 9/17 [00:02<00:02,  2.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

Extracting features for driving_00112:  59%|█████▉    | 10/17 [00:03<00:02,  3.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for driving_00112:  65%|██████▍   | 11/17 [00:03<00:01,  3.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for driving_00112:  71%|███████   | 12/17 [00:03<00:01,  2.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00112:  76%|███████▋  | 13/17 [00:04<00:01,  3.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00112:  82%|████████▏ | 14/17 [00:04<00:00,  3.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for driving_00112:  88%|████████▊ | 15/17 [00:04<00:00,  4.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00112:  94%|█████████▍| 16/17 [00:04<00:00,  4.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for driving_00112: 100%|██████████| 17/17 [00:04<00:00,  3.57it/s]
Extracting features for driving_00113:   0%|          | 0/16 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_00113:   6%|▋         | 1/16 [00:00<00:02,  5.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00113:  12%|█▎        | 2/16 [00:00<00:02,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00113:  19%|█▉        | 3/16 [00:00<00:02,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00113:  25%|██▌       | 4/16 [00:00<00:02,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00113:  31%|███▏      | 5/16 [00:00<00:02,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00113:  38%|███▊      | 6/16 [00:01<00:01,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00113:  44%|████▍     | 7/16 [00:01<00:01,  5.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for driving_00113:  50%|█████     | 8/16 [00:01<00:01,  5.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_00113:  56%|█████▋    | 9/16 [00:01<00:01,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00113:  62%|██████▎   | 10/16 [00:01<00:01,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00113:  69%|██████▉   | 11/16 [00:02<00:00,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00113:  75%|███████▌  | 12/16 [00:02<00:00,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00113:  81%|████████▏ | 13/16 [00:02<00:00,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00113:  88%|████████▊ | 14/16 [00:02<00:00,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00113:  94%|█████████▍| 15/16 [00:02<00:00,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00113: 100%|██████████| 16/16 [00:02<00:00,  5.37it/s]
Extracting features for driving_00114:   0%|          | 0/14 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00114:   7%|▋         | 1/14 [00:00<00:02,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00114:  14%|█▍        | 2/14 [00:00<00:02,  5.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00114:  21%|██▏       | 3/14 [00:00<00:01,  5.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00114:  29%|██▊       | 4/14 [00:00<00:01,  5.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00114:  36%|███▌      | 5/14 [00:00<00:01,  5.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00114:  43%|████▎     | 6/14 [00:01<00:01,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00114:  50%|█████     | 7/14 [00:01<00:01,  5.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00114:  57%|█████▋    | 8/14 [00:01<00:01,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00114:  64%|██████▍   | 9/14 [00:01<00:00,  5.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00114:  71%|███████▏  | 10/14 [00:01<00:00,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00114:  79%|███████▊  | 11/14 [00:02<00:00,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00114:  86%|████████▌ | 12/14 [00:02<00:00,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00114:  93%|█████████▎| 13/14 [00:02<00:00,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00114: 100%|██████████| 14/14 [00:02<00:00,  5.55it/s]
Extracting features for driving_00115:   0%|          | 0/19 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_00115:   5%|▌         | 1/19 [00:00<00:03,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for driving_00115:  11%|█         | 2/19 [00:00<00:03,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00115:  16%|█▌        | 3/19 [00:00<00:02,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00115:  21%|██        | 4/19 [00:00<00:03,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00115:  26%|██▋       | 5/19 [00:01<00:02,  4.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00115:  32%|███▏      | 6/19 [00:01<00:02,  4.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for driving_00115:  37%|███▋      | 7/19 [00:01<00:02,  4.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00115:  42%|████▏     | 8/19 [00:01<00:02,  4.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00115:  47%|████▋     | 9/19 [00:01<00:01,  5.14it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00115:  53%|█████▎    | 10/19 [00:02<00:01,  4.88it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00115:  58%|█████▊    | 11/19 [00:02<00:01,  4.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_00115:  63%|██████▎   | 12/19 [00:02<00:01,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00115:  68%|██████▊   | 13/19 [00:02<00:01,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00115:  74%|███████▎  | 14/19 [00:02<00:00,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_00115:  79%|███████▉  | 15/19 [00:02<00:00,  5.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step

Extracting features for driving_00115:  84%|████████▍ | 16/19 [00:03<00:00,  5.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00115:  89%|████████▉ | 17/19 [00:03<00:00,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step

Extracting features for driving_00115:  95%|█████████▍| 18/19 [00:03<00:00,  4.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

Extracting features for driving_00115: 100%|██████████| 19/19 [00:03<00:00,  4.79it/s]
Extracting features for driving_00116:   0%|          | 0/16 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

Extracting features for driving_00116:   6%|▋         | 1/16 [00:00<00:04,  3.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for driving_00116:  12%|█▎        | 2/16 [00:00<00:03,  3.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step

Extracting features for driving_00116:  19%|█▉        | 3/16 [00:00<00:03,  3.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step

Extracting features for driving_00116:  25%|██▌       | 4/16 [00:01<00:03,  3.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for driving_00116:  31%|███▏      | 5/16 [00:01<00:03,  3.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for driving_00116:  38%|███▊      | 6/16 [00:01<00:03,  3.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for driving_00116:  44%|████▍     | 7/16 [00:01<00:02,  3.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for driving_00116:  50%|█████     | 8/16 [00:02<00:02,  3.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step

Extracting features for driving_00116:  56%|█████▋    | 9/16 [00:02<00:02,  3.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step

Extracting features for driving_00116:  62%|██████▎   | 10/16 [00:03<00:02,  2.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

Extracting features for driving_00116:  69%|██████▉   | 11/16 [00:03<00:01,  3.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00116:  75%|███████▌  | 12/16 [00:03<00:01,  3.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00116:  81%|████████▏ | 13/16 [00:03<00:00,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00116:  88%|████████▊ | 14/16 [00:03<00:00,  4.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00116:  94%|█████████▍| 15/16 [00:04<00:00,  4.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00116: 100%|██████████| 16/16 [00:04<00:00,  3.73it/s]
Extracting features for driving_00117:   0%|          | 0/19 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00117:   5%|▌         | 1/19 [00:00<00:03,  5.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for driving_00117:  11%|█         | 2/19 [00:00<00:03,  5.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00117:  16%|█▌        | 3/19 [00:00<00:02,  5.57it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_00117:  21%|██        | 4/19 [00:00<00:02,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00117:  26%|██▋       | 5/19 [00:00<00:02,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00117:  32%|███▏      | 6/19 [00:01<00:02,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00117:  37%|███▋      | 7/19 [00:01<00:02,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

Extracting features for driving_00117:  42%|████▏     | 8/19 [00:01<00:02,  5.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00117:  47%|████▋     | 9/19 [00:01<00:01,  5.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00117:  53%|█████▎    | 10/19 [00:01<00:01,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00117:  58%|█████▊    | 11/19 [00:02<00:01,  5.28it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00117:  63%|██████▎   | 12/19 [00:02<00:01,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00117:  68%|██████▊   | 13/19 [00:02<00:01,  5.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for driving_00117:  74%|███████▎  | 14/19 [00:02<00:00,  5.29it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

Extracting features for driving_00117:  79%|███████▉  | 15/19 [00:02<00:00,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00117:  84%|████████▍ | 16/19 [00:03<00:00,  5.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00117:  89%|████████▉ | 17/19 [00:03<00:00,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00117:  95%|█████████▍| 18/19 [00:03<00:00,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_00117: 100%|██████████| 19/19 [00:03<00:00,  5.29it/s]
Extracting features for driving_00118:   0%|          | 0/18 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

Extracting features for driving_00118:   6%|▌         | 1/18 [00:00<00:03,  5.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00118:  11%|█         | 2/18 [00:00<00:02,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00118:  17%|█▋        | 3/18 [00:00<00:02,  5.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00118:  22%|██▏       | 4/18 [00:00<00:02,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00118:  28%|██▊       | 5/18 [00:00<00:02,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00118:  33%|███▎      | 6/18 [00:01<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00118:  39%|███▉      | 7/18 [00:01<00:01,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00118:  44%|████▍     | 8/18 [00:01<00:01,  5.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00118:  50%|█████     | 9/18 [00:01<00:01,  4.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00118:  56%|█████▌    | 10/18 [00:01<00:01,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for driving_00118:  61%|██████    | 11/18 [00:02<00:01,  5.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00118:  67%|██████▋   | 12/18 [00:02<00:01,  4.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00118:  72%|███████▏  | 13/18 [00:02<00:00,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00118:  78%|███████▊  | 14/18 [00:02<00:00,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00118:  83%|████████▎ | 15/18 [00:02<00:00,  5.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00118:  89%|████████▉ | 16/18 [00:03<00:00,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00118:  94%|█████████▍| 17/18 [00:03<00:00,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00118: 100%|██████████| 18/18 [00:03<00:00,  5.31it/s]
Extracting features for driving_00119:   0%|          | 0/17 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_00119:   6%|▌         | 1/17 [00:00<00:03,  5.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00119:  12%|█▏        | 2/17 [00:00<00:02,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00119:  18%|█▊        | 3/17 [00:00<00:02,  5.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00119:  24%|██▎       | 4/17 [00:00<00:02,  5.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00119:  29%|██▉       | 5/17 [00:00<00:02,  5.34it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00119:  35%|███▌      | 6/17 [00:01<00:02,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00119:  41%|████      | 7/17 [00:01<00:02,  5.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00119:  47%|████▋     | 8/17 [00:01<00:01,  4.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00119:  53%|█████▎    | 9/17 [00:01<00:01,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_00119:  59%|█████▉    | 10/17 [00:01<00:01,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step

Extracting features for driving_00119:  65%|██████▍   | 11/17 [00:02<00:01,  4.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

Extracting features for driving_00119:  71%|███████   | 12/17 [00:02<00:01,  4.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for driving_00119:  76%|███████▋  | 13/17 [00:02<00:00,  4.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for driving_00119:  82%|████████▏ | 14/17 [00:02<00:00,  4.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

Extracting features for driving_00119:  88%|████████▊ | 15/17 [00:03<00:00,  4.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step

Extracting features for driving_00119:  94%|█████████▍| 16/17 [00:03<00:00,  3.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for driving_00119: 100%|██████████| 17/17 [00:03<00:00,  4.39it/s]
Extracting features for driving_0012:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step

Extracting features for driving_0012:  25%|██▌       | 1/4 [00:00<00:01,  2.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step

Extracting features for driving_0012:  50%|█████     | 2/4 [00:00<00:00,  2.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for driving_0012:  75%|███████▌  | 3/4 [00:01<00:00,  3.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

Extracting features for driving_0012: 100%|██████████| 4/4 [00:01<00:00,  2.71it/s]
Extracting features for driving_00120:   0%|          | 0/5 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for driving_00120:  20%|██        | 1/5 [00:00<00:00,  4.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step

Extracting features for driving_00120:  40%|████      | 2/5 [00:00<00:00,  3.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00120:  60%|██████    | 3/5 [00:00<00:00,  4.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step

Extracting features for driving_00120:  80%|████████  | 4/5 [00:00<00:00,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00120: 100%|██████████| 5/5 [00:01<00:00,  4.82it/s]
Extracting features for driving_00121:   0%|          | 0/12 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

Extracting features for driving_00121:   8%|▊         | 1/12 [00:00<00:02,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00121:  17%|█▋        | 2/12 [00:00<00:01,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00121:  25%|██▌       | 3/12 [00:00<00:01,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00121:  33%|███▎      | 4/12 [00:00<00:01,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00121:  42%|████▏     | 5/12 [00:01<00:01,  5.06it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_00121:  50%|█████     | 6/12 [00:01<00:01,  5.16it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00121:  58%|█████▊    | 7/12 [00:01<00:00,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00121:  67%|██████▋   | 8/12 [00:01<00:00,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00121:  75%|███████▌  | 9/12 [00:01<00:00,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

Extracting features for driving_00121:  83%|████████▎ | 10/12 [00:01<00:00,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00121:  92%|█████████▏| 11/12 [00:02<00:00,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00121: 100%|██████████| 12/12 [00:02<00:00,  5.31it/s]
Extracting features for driving_00122:   0%|          | 0/16 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

Extracting features for driving_00122:   6%|▋         | 1/16 [00:00<00:03,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00122:  12%|█▎        | 2/16 [00:00<00:03,  4.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

Extracting features for driving_00122:  19%|█▉        | 3/16 [00:00<00:02,  4.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00122:  25%|██▌       | 4/16 [00:00<00:02,  5.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00122:  31%|███▏      | 5/16 [00:01<00:02,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00122:  38%|███▊      | 6/16 [00:01<00:01,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00122:  44%|████▍     | 7/16 [00:01<00:01,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_00122:  50%|█████     | 8/16 [00:01<00:01,  5.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00122:  56%|█████▋    | 9/16 [00:01<00:01,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00122:  62%|██████▎   | 10/16 [00:01<00:01,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00122:  69%|██████▉   | 11/16 [00:02<00:00,  5.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00122:  75%|███████▌  | 12/16 [00:02<00:00,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00122:  81%|████████▏ | 13/16 [00:02<00:00,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for driving_00122:  88%|████████▊ | 14/16 [00:02<00:00,  5.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00122:  94%|█████████▍| 15/16 [00:02<00:00,  5.40it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00122: 100%|██████████| 16/16 [00:03<00:00,  5.22it/s]
Extracting features for driving_00123:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_00123:   5%|▌         | 1/20 [00:00<00:03,  5.32it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00123:  10%|█         | 2/20 [00:00<00:03,  5.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00123:  15%|█▌        | 3/20 [00:00<00:03,  5.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_00123:  20%|██        | 4/20 [00:00<00:02,  5.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00123:  25%|██▌       | 5/20 [00:00<00:02,  5.04it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_00123:  30%|███       | 6/20 [00:01<00:02,  5.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00123:  35%|███▌      | 7/20 [00:01<00:02,  5.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00123:  40%|████      | 8/20 [00:01<00:02,  5.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00123:  45%|████▌     | 9/20 [00:01<00:01,  5.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00123:  50%|█████     | 10/20 [00:01<00:01,  5.43it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00123:  55%|█████▌    | 11/20 [00:02<00:01,  5.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00123:  60%|██████    | 12/20 [00:02<00:01,  5.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00123:  65%|██████▌   | 13/20 [00:02<00:01,  5.48it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00123:  70%|███████   | 14/20 [00:02<00:01,  5.07it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00123:  75%|███████▌  | 15/20 [00:02<00:00,  5.18it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00123:  80%|████████  | 16/20 [00:03<00:00,  4.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00123:  85%|████████▌ | 17/20 [00:03<00:00,  5.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00123:  90%|█████████ | 18/20 [00:03<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00123:  95%|█████████▌| 19/20 [00:03<00:00,  5.45it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00123: 100%|██████████| 20/20 [00:03<00:00,  5.31it/s]
Extracting features for driving_00124:   0%|          | 0/20 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_00124:   5%|▌         | 1/20 [00:00<00:04,  4.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step

Extracting features for driving_00124:  10%|█         | 2/20 [00:00<00:04,  3.93it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step

Extracting features for driving_00124:  15%|█▌        | 3/20 [00:00<00:04,  3.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step

Extracting features for driving_00124:  20%|██        | 4/20 [00:01<00:04,  3.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step

Extracting features for driving_00124:  25%|██▌       | 5/20 [00:01<00:05,  2.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for driving_00124:  30%|███       | 6/20 [00:01<00:04,  3.22it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for driving_00124:  35%|███▌      | 7/20 [00:02<00:03,  3.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step

Extracting features for driving_00124:  40%|████      | 8/20 [00:02<00:04,  2.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step

Extracting features for driving_00124:  45%|████▌     | 9/20 [00:02<00:03,  3.21it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step

Extracting features for driving_00124:  50%|█████     | 10/20 [00:02<00:02,  3.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step

Extracting features for driving_00124:  55%|█████▌    | 11/20 [00:03<00:02,  3.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step

Extracting features for driving_00124:  60%|██████    | 12/20 [00:03<00:02,  3.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step

Extracting features for driving_00124:  65%|██████▌   | 13/20 [00:03<00:01,  3.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step

Extracting features for driving_00124:  70%|███████   | 14/20 [00:04<00:01,  3.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00124:  75%|███████▌  | 15/20 [00:04<00:01,  3.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

Extracting features for driving_00124:  80%|████████  | 16/20 [00:04<00:01,  3.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00124:  85%|████████▌ | 17/20 [00:04<00:00,  4.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_00124:  90%|█████████ | 18/20 [00:04<00:00,  4.50it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00124:  95%|█████████▌| 19/20 [00:05<00:00,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00124: 100%|██████████| 20/20 [00:05<00:00,  3.76it/s]
Extracting features for driving_00125:   0%|          | 0/19 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

Extracting features for driving_00125:   5%|▌         | 1/19 [00:00<00:03,  4.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00125:  11%|█         | 2/19 [00:00<00:03,  5.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_00125:  16%|█▌        | 3/19 [00:00<00:02,  5.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_00125:  21%|██        | 4/19 [00:00<00:02,  5.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_00125:  26%|██▋       | 5/19 [00:00<00:02,  5.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_00125:  32%|███▏      | 6/19 [00:01<00:02,  5.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

Extracting features for driving_00125:  37%|███▋      | 7/19 [00:01<00:02,  4.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00125:  42%|████▏     | 8/19 [00:01<00:02,  5.19it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00125:  47%|████▋     | 9/19 [00:01<00:01,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_00125:  53%|█████▎    | 10/19 [00:01<00:01,  5.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_00125:  58%|█████▊    | 11/19 [00:02<00:01,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_00125:  63%|██████▎   | 12/19 [00:02<00:01,  5.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_00125:  68%|██████▊   | 13/19 [00:02<00:01,  5.31it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_00125:  74%|███████▎  | 14/19 [00:02<00:00,  5.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00125:  79%|███████▉  | 15/19 [00:02<00:00,  5.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_00125:  84%|████████▍ | 16/19 [00:02<00:00,  5.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_00125:  89%|████████▉ | 17/19 [00:03<00:00,  5.15it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_00125:  95%|█████████▍| 18/19 [00:03<00:00,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_00125: 100%|██████████| 19/19 [00:03<00:00,  5.24it/s]
Extracting features for driving_0013:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_0013:  25%|██▌       | 1/4 [00:00<00:00,  3.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_0013:  50%|█████     | 2/4 [00:00<00:00,  4.71it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_0013:  75%|███████▌  | 3/4 [00:00<00:00,  4.41it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_0013: 100%|██████████| 4/4 [00:00<00:00,  4.55it/s]
Extracting features for driving_0014:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_0014:  25%|██▌       | 1/4 [00:00<00:00,  4.92it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_0014:  50%|█████     | 2/4 [00:00<00:00,  5.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_0014:  75%|███████▌  | 3/4 [00:00<00:00,  5.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for driving_0014: 100%|██████████| 4/4 [00:00<00:00,  4.98it/s]
Extracting features for driving_0015:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_0015:  25%|██▌       | 1/4 [00:00<00:00,  5.03it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_0015:  50%|█████     | 2/4 [00:00<00:00,  4.39it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0015:  75%|███████▌  | 3/4 [00:00<00:00,  4.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_0015: 100%|██████████| 4/4 [00:00<00:00,  4.60it/s]
Extracting features for driving_0016:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step

Extracting features for driving_0016:  25%|██▌       | 1/4 [00:00<00:00,  4.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_0016:  50%|█████     | 2/4 [00:00<00:00,  4.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_0016:  75%|███████▌  | 3/4 [00:00<00:00,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_0016: 100%|██████████| 4/4 [00:00<00:00,  4.82it/s]
Extracting features for driving_0017:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

Extracting features for driving_0017:  25%|██▌       | 1/4 [00:00<00:00,  3.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_0017:  50%|█████     | 2/4 [00:00<00:00,  4.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_0017:  75%|███████▌  | 3/4 [00:00<00:00,  5.00it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_0017: 100%|██████████| 4/4 [00:00<00:00,  4.97it/s]
Extracting features for driving_0018:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_0018:  25%|██▌       | 1/4 [00:00<00:00,  5.11it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_0018:  50%|█████     | 2/4 [00:00<00:00,  5.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

Extracting features for driving_0018:  75%|███████▌  | 3/4 [00:00<00:00,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0018: 100%|██████████| 4/4 [00:00<00:00,  5.01it/s]
Extracting features for driving_0019:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

Extracting features for driving_0019:  25%|██▌       | 1/4 [00:00<00:00,  4.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

Extracting features for driving_0019:  50%|█████     | 2/4 [00:00<00:00,  3.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step

Extracting features for driving_0019:  75%|███████▌  | 3/4 [00:00<00:00,  3.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step

Extracting features for driving_0019: 100%|██████████| 4/4 [00:01<00:00,  3.62it/s]
Extracting features for driving_002:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step

Extracting features for driving_002:  25%|██▌       | 1/4 [00:00<00:00,  3.02it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for driving_002:  50%|█████     | 2/4 [00:00<00:00,  3.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step

Extracting features for driving_002:  75%|███████▌  | 3/4 [00:00<00:00,  3.47it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step

Extracting features for driving_002: 100%|██████████| 4/4 [00:01<00:00,  3.49it/s]
Extracting features for driving_0020:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step

Extracting features for driving_0020:  25%|██▌       | 1/4 [00:00<00:00,  3.20it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step

Extracting features for driving_0020:  50%|█████     | 2/4 [00:00<00:00,  2.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

Extracting features for driving_0020:  75%|███████▌  | 3/4 [00:01<00:00,  2.90it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step

Extracting features for driving_0020: 100%|██████████| 4/4 [00:01<00:00,  2.64it/s]
Extracting features for driving_0021:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step

Extracting features for driving_0021:  25%|██▌       | 1/4 [00:00<00:00,  3.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_0021:  50%|█████     | 2/4 [00:00<00:00,  3.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0021:  75%|███████▌  | 3/4 [00:00<00:00,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_0021: 100%|██████████| 4/4 [00:00<00:00,  4.38it/s]
Extracting features for driving_0022:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_0022:  25%|██▌       | 1/4 [00:00<00:00,  4.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

Extracting features for driving_0022:  50%|█████     | 2/4 [00:00<00:00,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_0022:  75%|███████▌  | 3/4 [00:00<00:00,  4.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_0022: 100%|██████████| 4/4 [00:00<00:00,  4.81it/s]
Extracting features for driving_0023:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_0023:  25%|██▌       | 1/4 [00:00<00:00,  4.79it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_0023:  50%|█████     | 2/4 [00:00<00:00,  4.83it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_0023:  75%|███████▌  | 3/4 [00:00<00:00,  4.35it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0023: 100%|██████████| 4/4 [00:00<00:00,  4.41it/s]
Extracting features for driving_0024:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_0024:  25%|██▌       | 1/4 [00:00<00:00,  4.91it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_0024:  50%|█████     | 2/4 [00:00<00:00,  4.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_0024:  75%|███████▌  | 3/4 [00:00<00:00,  4.49it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_0024: 100%|██████████| 4/4 [00:00<00:00,  4.77it/s]
Extracting features for driving_0025:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_0025:  25%|██▌       | 1/4 [00:00<00:00,  3.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_0025:  50%|█████     | 2/4 [00:00<00:00,  4.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_0025:  75%|███████▌  | 3/4 [00:00<00:00,  4.44it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

Extracting features for driving_0025: 100%|██████████| 4/4 [00:00<00:00,  4.58it/s]
Extracting features for driving_0026:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_0026:  25%|██▌       | 1/4 [00:00<00:00,  4.10it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_0026:  50%|█████     | 2/4 [00:00<00:00,  4.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

Extracting features for driving_0026:  75%|███████▌  | 3/4 [00:00<00:00,  4.54it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0026: 100%|██████████| 4/4 [00:00<00:00,  4.57it/s]
Extracting features for driving_0027:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

Extracting features for driving_0027:  25%|██▌       | 1/4 [00:00<00:00,  3.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_0027:  50%|█████     | 2/4 [00:00<00:00,  4.64it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_0027:  75%|███████▌  | 3/4 [00:00<00:00,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_0027: 100%|██████████| 4/4 [00:00<00:00,  4.79it/s]
Extracting features for driving_0028:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step

Extracting features for driving_0028:  25%|██▌       | 1/4 [00:00<00:00,  4.78it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_0028:  50%|█████     | 2/4 [00:00<00:00,  4.73it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step

Extracting features for driving_0028:  75%|███████▌  | 3/4 [00:00<00:00,  5.08it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_0028: 100%|██████████| 4/4 [00:00<00:00,  5.06it/s]
Extracting features for driving_0029:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for driving_0029:  25%|██▌       | 1/4 [00:00<00:00,  4.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_0029:  50%|█████     | 2/4 [00:00<00:00,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step

Extracting features for driving_0029:  75%|███████▌  | 3/4 [00:00<00:00,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_0029: 100%|██████████| 4/4 [00:00<00:00,  4.87it/s]
Extracting features for driving_003:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step

Extracting features for driving_003:  25%|██▌       | 1/4 [00:00<00:00,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_003:  50%|█████     | 2/4 [00:00<00:00,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_003:  75%|███████▌  | 3/4 [00:00<00:00,  4.77it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_003: 100%|██████████| 4/4 [00:00<00:00,  4.72it/s]
Extracting features for driving_0030:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step

Extracting features for driving_0030:  25%|██▌       | 1/4 [00:00<00:00,  3.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step

Extracting features for driving_0030:  50%|█████     | 2/4 [00:00<00:00,  4.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_0030:  75%|███████▌  | 3/4 [00:00<00:00,  4.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

Extracting features for driving_0030: 100%|██████████| 4/4 [00:00<00:00,  4.60it/s]
Extracting features for driving_0031:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step

Extracting features for driving_0031:  25%|██▌       | 1/4 [00:00<00:00,  4.55it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_0031:  50%|█████     | 2/4 [00:00<00:00,  4.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_0031:  75%|███████▌  | 3/4 [00:00<00:00,  4.85it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_0031: 100%|██████████| 4/4 [00:00<00:00,  4.87it/s]
Extracting features for driving_0032:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step

Extracting features for driving_0032:  25%|██▌       | 1/4 [00:00<00:00,  3.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

Extracting features for driving_0032:  50%|█████     | 2/4 [00:00<00:00,  3.63it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step

Extracting features for driving_0032:  75%|███████▌  | 3/4 [00:00<00:00,  3.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step

Extracting features for driving_0032: 100%|██████████| 4/4 [00:01<00:00,  3.63it/s]
Extracting features for driving_0033:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step

Extracting features for driving_0033:  25%|██▌       | 1/4 [00:00<00:00,  3.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step

Extracting features for driving_0033:  50%|█████     | 2/4 [00:00<00:00,  3.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step

Extracting features for driving_0033:  75%|███████▌  | 3/4 [00:00<00:00,  3.65it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step

Extracting features for driving_0033: 100%|██████████| 4/4 [00:01<00:00,  3.65it/s]
Extracting features for driving_0034:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step

Extracting features for driving_0034:  25%|██▌       | 1/4 [00:00<00:00,  3.13it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step

Extracting features for driving_0034:  50%|█████     | 2/4 [00:00<00:00,  3.09it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step

Extracting features for driving_0034:  75%|███████▌  | 3/4 [00:00<00:00,  3.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step

Extracting features for driving_0034: 100%|██████████| 4/4 [00:01<00:00,  3.24it/s]
Extracting features for driving_0035:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step

Extracting features for driving_0035:  25%|██▌       | 1/4 [00:00<00:00,  3.67it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step

Extracting features for driving_0035:  50%|█████     | 2/4 [00:00<00:00,  2.62it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step

Extracting features for driving_0035:  75%|███████▌  | 3/4 [00:01<00:00,  2.87it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_0035: 100%|██████████| 4/4 [00:01<00:00,  3.19it/s]
Extracting features for driving_0036:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

Extracting features for driving_0036:  25%|██▌       | 1/4 [00:00<00:00,  4.38it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_0036:  50%|█████     | 2/4 [00:00<00:00,  4.99it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step

Extracting features for driving_0036:  75%|███████▌  | 3/4 [00:00<00:00,  5.33it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_0036: 100%|██████████| 4/4 [00:00<00:00,  5.14it/s]
Extracting features for driving_0037:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step

Extracting features for driving_0037:  25%|██▌       | 1/4 [00:00<00:00,  4.74it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for driving_0037:  50%|█████     | 2/4 [00:00<00:00,  4.66it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_0037:  75%|███████▌  | 3/4 [00:00<00:00,  4.82it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step

Extracting features for driving_0037: 100%|██████████| 4/4 [00:00<00:00,  4.60it/s]
Extracting features for driving_0038:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for driving_0038:  25%|██▌       | 1/4 [00:00<00:00,  3.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0038:  50%|█████     | 2/4 [00:00<00:00,  4.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0038:  75%|███████▌  | 3/4 [00:00<00:00,  4.27it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_0038: 100%|██████████| 4/4 [00:00<00:00,  4.28it/s]
Extracting features for driving_0039:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0039:  25%|██▌       | 1/4 [00:00<00:00,  3.95it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step

Extracting features for driving_0039:  50%|█████     | 2/4 [00:00<00:00,  4.76it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0039:  75%|███████▌  | 3/4 [00:00<00:00,  4.96it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step

Extracting features for driving_0039: 100%|██████████| 4/4 [00:00<00:00,  4.55it/s]
Extracting features for driving_004:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_004:  25%|██▌       | 1/4 [00:00<00:00,  4.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step

Extracting features for driving_004:  50%|█████     | 2/4 [00:00<00:00,  4.68it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_004:  75%|███████▌  | 3/4 [00:00<00:00,  4.37it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_004: 100%|██████████| 4/4 [00:00<00:00,  4.50it/s]
Extracting features for driving_0040:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

Extracting features for driving_0040:  25%|██▌       | 1/4 [00:00<00:00,  4.70it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_0040:  50%|█████     | 2/4 [00:00<00:00,  4.97it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step

Extracting features for driving_0040:  75%|███████▌  | 3/4 [00:00<00:00,  4.52it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step

Extracting features for driving_0040: 100%|██████████| 4/4 [00:00<00:00,  4.50it/s]
Extracting features for driving_0041:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_0041:  25%|██▌       | 1/4 [00:00<00:00,  4.51it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step

Extracting features for driving_0041:  50%|█████     | 2/4 [00:00<00:00,  5.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step

Extracting features for driving_0041:  75%|███████▌  | 3/4 [00:00<00:00,  5.17it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_0041: 100%|██████████| 4/4 [00:00<00:00,  5.11it/s]
Extracting features for driving_005:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step

Extracting features for driving_005:  25%|██▌       | 1/4 [00:00<00:00,  4.81it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step

Extracting features for driving_005:  50%|█████     | 2/4 [00:00<00:00,  4.75it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_005:  75%|███████▌  | 3/4 [00:00<00:00,  4.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step

Extracting features for driving_005: 100%|██████████| 4/4 [00:00<00:00,  4.96it/s]
Extracting features for driving_006:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

Extracting features for driving_006:  25%|██▌       | 1/4 [00:00<00:00,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_006:  50%|█████     | 2/4 [00:00<00:00,  4.53it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_006:  75%|███████▌  | 3/4 [00:00<00:00,  4.25it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_006: 100%|██████████| 4/4 [00:00<00:00,  4.49it/s]
Extracting features for driving_007:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step

Extracting features for driving_007:  25%|██▌       | 1/4 [00:00<00:00,  4.46it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step

Extracting features for driving_007:  50%|█████     | 2/4 [00:00<00:00,  4.89it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step

Extracting features for driving_007:  75%|███████▌  | 3/4 [00:00<00:00,  5.05it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_007: 100%|██████████| 4/4 [00:00<00:00,  4.93it/s]
Extracting features for driving_008:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step

Extracting features for driving_008:  25%|██▌       | 1/4 [00:00<00:00,  4.59it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Extracting features for driving_008:  50%|█████     | 2/4 [00:00<00:00,  4.86it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step

Extracting features for driving_008:  75%|███████▌  | 3/4 [00:00<00:00,  4.98it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step

Extracting features for driving_008: 100%|██████████| 4/4 [00:00<00:00,  4.89it/s]
Extracting features for driving_009:   0%|          | 0/4 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

Extracting features for driving_009:  25%|██▌       | 1/4 [00:00<00:00,  4.36it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step

Extracting features for driving_009:  50%|█████     | 2/4 [00:00<00:00,  4.61it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step

Extracting features for driving_009:  75%|███████▌  | 3/4 [00:00<00:00,  3.84it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

Extracting features for driving_009: 100%|██████████| 4/4 [00:01<00:00,  3.35it/s]

In [ ]:
# You can now inspect the extracted features
# For example, print the shape of features for one video
print(video_features['accident_000'].shape)

(25, 1280)

# dataset preparation

In [ ]:
import glob
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.sequence import pad_sequences
y = np.array([1 if label == 'accident' else 0 for label in df['case']])

# Extract the feature arrays from the dictionary
video_feature_list = list(video_features.values())

x = pad_sequences(video_feature_list, padding='post', dtype='float32')

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.2,
                                                    stratify=y,
                                                    random_state=42)

# trainig the model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Define the LSTM model
model = Sequential()
model.add(LSTM(128, return_sequences=True, input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Dropout(0.2))
model.add(LSTM(64))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_4 (LSTM)                   │ (None, 40, 128)        │       721,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 40, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 770,881 (2.94 MB)

 Trainable params: 770,881 (2.94 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=8,
                    validation_split=0.2)

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 6s 212ms/step - accuracy: 0.5296 - loss: 0.6551 - val_accuracy: 0.8182 - val_loss: 0.6447
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 136ms/step - accuracy: 0.9618 - loss: 0.2888 - val_accuracy: 1.0000 - val_loss: 0.0722
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 160ms/step - accuracy: 0.9882 - loss: 0.1052 - val_accuracy: 0.9091 - val_loss: 0.3542
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - accuracy: 0.9261 - loss: 0.2617 - val_accuracy: 0.9091 - val_loss: 0.1974
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 0.9663 - loss: 0.1530 - val_accuracy: 0.9091 - val_loss: 0.3058
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 107ms/step - accuracy: 0.9061 - loss: 0.2912 - val_accuracy: 0.9091 - val_loss: 0.2995
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.9364 - loss: 0.2392 - val_accuracy: 0.8636 - val_loss: 0.3323
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - accuracy: 0.9062 - loss: 0.2466 - val_accuracy: 0.8636 - val_loss: 0.3068
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 163ms/step - accuracy: 0.9861 - loss: 0.1093 - val_accuracy: 0.9091 - val_loss: 0.2638
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 155ms/step - accuracy: 0.9961 - loss: 0.0460 - val_accuracy: 0.9091 - val_loss: 0.3428

In [ ]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {accuracy*100:.2f}%")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.9643 - loss: 0.1512
Test Accuracy: 96.43%

In [ ]:
model.save("/content/drive/MyDrive/model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

# prediction

In [ ]:
import numpy as np
import cv2, os, glob
from tensorflow.keras.models import load_model
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load trained LSTM model
model = load_model("/content/drive/MyDrive/model.h5")

# Load feature extractor
feature_extractor = EfficientNetB0(weights='imagenet', include_top=False, pooling='avg')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
def extract_frames(video_path, every_n_frames=10):
    frames = []
    cap = cv2.VideoCapture(video_path)
    frame_id = 0
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        if frame_id % every_n_frames == 0:
            frames.append(frame)
        frame_id += 1
    cap.release()
    return frames

In [ ]:
def extract_video_features(video_path):
    frames = extract_frames(video_path, every_n_frames=10)
    features = []
    for frame in frames:
        img = cv2.resize(frame, (224, 224))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x)
        feat = feature_extractor.predict(x, verbose=0)
        features.append(feat[0])
    return np.array(features)

In [ ]:
def predict_video(video_path):
    features = extract_video_features(video_path)
    X = pad_sequences([features], padding='post', dtype='float32', maxlen=model.input_shape[1])
    pred = model.predict(X)
    label = "Accident" if pred[0][0] > 0.5 else "Normal Driving"
    print(f"Prediction: {label} (Confidence: {pred[0][0]:.2f})")

In [ ]:
video_path = "/content/drive/MyDrive/train/training_videos/accident_0020.mp4"
predict_video(video_path)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 467ms/step
Prediction: Accident (Confidence: 1.00)